/*
SQLyog Community v13.1.7 (64 bit)
MySQL - 5.7.29-log : Database - zblog
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`zblog` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `zblog`;

/*Table structure for table `persistent_logins` */
DROP TABLE IF EXISTS `persistent_logins`;
CREATE TABLE `persistent_logins` (
  `username` varchar(64) NOT NULL,
  `series` varchar(64) NOT NULL,
  `token` varchar(64) NOT NULL,
  `last_used` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`series`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

/*Table structure for table `user` */
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `NICKNAME` VARCHAR(20) NOT NULL COMMENT '昵称',
  `USERNAME` VARCHAR(20) NOT NULL COMMENT '用户名',
  `PASSWORD` VARCHAR(60) NOT NULL COMMENT '密码',
  `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `TELEPHONE` VARCHAR(11) DEFAULT NULL COMMENT '手机号',
  `QQ` VARCHAR(15) DEFAULT NULL COMMENT 'QQ',
  `GENDER` TINYINT(2) NOT NULL COMMENT '性别: 1-男;2-女;3-隐藏',
  `SIGNATURE` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '签名',
  `HEAD_IMG_URL` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '头像地址',
  `LOGIN_TIME` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '最后一次登录时间',
  `CHANGE_PWD_TIME` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '最后一次修改密码时间',
  `CHANGE_PWD` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要登陆修改密码',
  `LOCKED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '账户是否登录锁定',
  `TEMP` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否是临时账户',
  `EXPIRED_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '临时账户的过期时间',
  `ADMIN` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否是系统管理员',
  `BUILD_IN` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否是内置用户',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX USERNAME_INDEX (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户表';

/*Data for the table `user` */
INSERT INTO user (ID, NICKNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, QQ, GENDER, SIGNATURE, HEAD_IMG_URL, LOGIN_TIME, CHANGE_PWD_TIME, LOCKED, TEMP, EXPIRED_TIME, ADMIN, BUILD_IN, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, '管理员', 'admin', '$2a$10$S9s8OySDf1B.0HerBauT1.QnrrOzsmAOU7rTXhVJL3UY2Z02Ul6FG', 'stazxr@qq.com', '', '', '3', 'https://github.com/stazxr/zblog', '', '', '', 0, 0, '', 1, 1, 1, 0, 1, 'system', '2021-05-17 01:48:00', '2021-05-17', '', '');

/*Table structure for table `role` */
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ROLE_NAME` VARCHAR(25) NOT NULL COMMENT '角色名称',
  `ROLE_CODE` VARCHAR(25) NOT NULL COMMENT '角色编码',
  `DESC` VARCHAR(127) NOT NULL DEFAULT '' COMMENT '角色描述',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '角色状态',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX ROLE_CODE_INDEX (`ROLE_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='角色表';

/*Table structure for table `user_role_relation` */
DROP TABLE IF EXISTS `user_role_relation`;
CREATE TABLE `user_role_relation` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `USER_ID` BIGINT(64) NOT NULL COMMENT '用户编号',
  `ROLE_ID` BIGINT(64) NOT NULL COMMENT '角色编号',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_USER_ROLE` (`USER_ID`, `ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户角色关联表';

/*Table structure for table `permission` */
DROP TABLE IF EXISTS `permission`;
CREATE TABLE `permission` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `PID` BIGINT(64) DEFAULT NULL COMMENT '上级权限编号',
  `PERM_NAME` VARCHAR(50) NOT NULL COMMENT '目录名称/菜单名称/权限名称',
  `PERM_TYPE` TINYINT(5) NOT NULL COMMENT '权限类型: 1-目录;2-菜单;3-按钮',
  `PERM_CODE` VARCHAR(100) DEFAULT NULL COMMENT '权限编码',
  `PERM_LEVEL` TINYINT(5) NOT NULL COMMENT '访问级别: 1-公开权限;2-公共权限;3-受控权限',
  `COMPONENT_NAME` VARCHAR(50) DEFAULT NULL COMMENT '组件名称',
  `COMPONENT_PATH` VARCHAR(100) DEFAULT NULL COMMENT '组件路径',
  `ROUTER_PATH` VARCHAR(1000) DEFAULT NULL COMMENT '前端路由地址',
  `ICON` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '权限图标（只有目录和菜单有）',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序字段',
  `CACHE` TINYINT(1) DEFAULT NULL COMMENT '是否缓存',
  `HIDDEN` TINYINT(1) DEFAULT NULL COMMENT '是否隐藏',
  `I_FRAME` TINYINT(1) DEFAULT NULL COMMENT '是否外链',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_PID` (`PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='权限表';

/*Data for the table `permission` */
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, null, '系统管理', 1, null, 3, null, null, 'system', 'system', 1, null, 0, 0, 1, 0, 1, 'admin', '2021-06-10 00:02:58', '2021-06-10', 'admin', '2022-09-20 09:11:45');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (2, 1, '用户管理', 2, 'queryUserListByPage', 3, 'User', 'admin/system/user/index', 'user', 'peoples', 11, 1, 0, 0, 1, 0, 1, 'admin', '2021-06-10 00:02:58', '2021-06-10', 'admin', '2022-09-20 11:41:38');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3, 1, '角色管理', 2, 'queryRoleListByPage', 3, 'Role', 'admin/system/role/index', 'role', 'role', 12, 0, 0, 0, 1, 0, 1, 'admin', '2021-06-10 00:02:58', '2021-06-10', 'admin', '2022-09-20 11:41:55');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (4, 1, '权限管理', 2, 'queryPermTreeList', 3, 'Perm', 'admin/system/perm/index', 'perm', 'menu', 13, 1, 0, 0, 1, 0, 1, 'admin', '2021-06-10 00:02:58', '2021-06-10', 'admin', '2022-09-20 11:42:29');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1563578517417664513, 4, '新增权限', 3, 'addPerm', 3, null, null, null, '', 131, null, null, null, 1, 0, 1, 'admin', '2022-08-28 01:25:43', '2022-08-28', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1563579044557791234, 4, '编辑权限', 3, 'editPerm', 3, null, null, null, '', 132, null, null, null, 1, 0, 1, 'admin', '2022-08-28 01:27:48', '2022-08-28', 'admin', '2022-08-28 13:53:01');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1563580310390349825, 4, '删除权限', 3, 'deletePerm', 3, null, null, null, '', 133, null, null, null, 1, 0, 1, 'admin', '2022-08-28 01:32:50', '2022-08-28', 'admin', '2022-08-28 13:43:11');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569014424474853378, 4, '查询权限详情', 3, 'queryPermDetail', 3, null, null, null, '', 130, null, null, null, 1, 0, 1, 'admin', '2022-09-12 01:26:04', '2022-09-12', 'admin', '2022-09-12 01:45:22');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569307396374384642, 3, '新增角色', 3, 'addRole', 3, null, null, null, '', 120, null, null, null, 1, 0, 1, 'admin', '2022-09-12 20:50:14', '2022-09-12', 'admin', '2022-10-11 19:10:25');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569307578382012417, 3, '编辑角色', 3, 'editRole', 3, null, null, null, '', 121, null, null, null, 1, 0, 1, 'admin', '2022-09-12 20:50:57', '2022-09-12', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569307648452055041, 3, '删除角色', 3, 'deleteRole', 3, null, null, null, '', 122, null, null, null, 1, 0, 1, 'admin', '2022-09-12 20:51:14', '2022-09-12', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569307755872374786, 3, '角色授权', 3, 'authRole', 3, null, null, null, '', 123, null, null, null, 1, 0, 1, 'admin', '2022-09-12 20:51:39', '2022-09-12', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569658370598395906, 4, '批量删除角色权限', 3, 'batchDeleteRolePerm', 3, null, null, null, '', 134, null, null, null, 1, 0, 1, 'admin', '2022-09-13 20:04:53', '2022-09-13', 'admin', '2022-09-13 20:08:07');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569658931083239426, 3, '查询角色用户列表', 3, 'pageUsersByRoleId', 3, null, null, null, '', 124, null, null, null, 1, 0, 1, 'admin', '2022-09-13 20:07:06', '2022-09-13', 'admin', '2022-09-13 20:07:33');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569659298403606530, 3, '批量删除角色用户', 3, 'batchDeleteUserRole', 3, null, null, null, '', 126, null, null, null, 1, 0, 1, 'admin', '2022-09-13 20:08:34', '2022-09-13', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569659511331643394, 3, '批量新增角色用户', 3, 'batchAddUserRole', 3, null, null, null, '', 125, null, null, null, 1, 0, 1, 'admin', '2022-09-13 20:09:25', '2022-09-13', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1569891040041467905, 2, '新增用户', 3, 'addUser', 3, null, null, null, '', 111, null, null, null, 1, 0, 1, 'admin', '2022-09-14 11:29:25', '2022-09-14', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3509022992757686272, 2, '编辑用户', 3, 'editUser', 3, null, null, null, '', 112, null, null, null, 1, 0, 1, 'admin', '2022-09-15 01:24:35', '2022-09-15', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3509023104661716992, 2, '删除用户', 3, 'deleteUser', 3, null, null, null, '', 113, null, null, null, 1, 0, 1, 'admin', '2022-09-15 01:25:02', '2022-09-15', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3509256368773136384, 2, '查询用户详情', 3, 'queryUserDetail', 3, null, null, null, '', 110, null, null, null, 1, 0, 1, 'admin', '2022-09-15 16:51:57', '2022-09-15', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3509256563372064768, 2, '启用 / 禁用用户', 3, 'updateUserStatus', 3, null, null, null, '', 114, null, null, null, 1, 0, 1, 'admin', '2022-09-15 16:52:43', '2022-09-15', 'admin', '2022-10-10 16:47:22');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3509530538144694272, 1, '路由管理', 2, null, 3, 'Router', 'admin/system/router/index', 'router', 'tree-table', 14, 1, 0, 0, 1, 0, 1, 'admin', '2022-09-16 11:01:24', '2022-09-16', 'admin', '2022-10-10 16:14:20');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3510333378140307456, null, '系统监控', 1, null, 3, null, null, 'monitor', 'monitor', 2, null, 0, 0, 1, 0, 1, 'admin', '2022-09-18 16:11:36', '2022-09-18', 'admin', '2022-09-20 09:28:29');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3510991230819368960, 1, '字典管理', 2, 'queryDictListByPage', 3, 'Dict', 'admin/system/dict/index', 'dict', 'education', 15, 1, 0, 0, 1, 0, 1, 'admin', '2022-09-20 11:45:40', '2022-09-20', 'admin', '2022-10-09 10:12:31');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3510991704482119680, 3510333378140307456, '操作日志', 2, 'queryOperateLogsByPage', 3, 'OperateLog', 'admin/monitor/operatorLog/index', 'operateLog', 'log', 21, 1, 0, 0, 1, 0, 1, 'admin', '2022-09-20 11:47:33', '2022-09-20', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3510991881443999744, 3510333378140307456, '接口日志', 2, 'queryApiLogsByPage', 3, 'ApiLog', 'admin/monitor/apiLog/index', 'apiLog', 'skill', 22, 1, 0, 0, 1, 0, 1, 'admin', '2022-09-20 11:48:15', '2022-09-20', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511169961735225344, 3509530538144694272, '打开 / 关闭日志展示', 3, 'updateLogShowStatus', 3, null, null, null, '', 145, null, null, null, 1, 0, 1, 'admin', '2022-09-20 23:35:53', '2022-09-20', 'admin', '2022-10-10 16:15:57');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511170174386438144, 3509530538144694272, '黑白名单列表查询', 3, 'pageBlackOrWhiteList', 3, null, null, null, '', 141, null, null, null, 1, 0, 1, 'admin', '2022-09-20 23:36:43', '2022-09-20', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511181946661109760, 3509530538144694272, '新增黑白名单', 3, 'addBlackOrWhiteRouter', 3, null, null, null, '', 142, null, null, null, 1, 0, 1, 'admin', '2022-09-21 00:23:30', '2022-09-21', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511182018656337920, 3509530538144694272, '编辑黑白名单', 3, 'editBlackOrWhiteRouter', 3, null, null, null, '', 143, null, null, null, 1, 0, 1, 'admin', '2022-09-21 00:23:47', '2022-09-21', 'admin', '2022-09-21 00:24:16');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511182110150885376, 3509530538144694272, '启用 / 禁用黑白名单状态', 3, 'changeBlackOrWhiteRouterStatus', 3, null, null, null, '', 146, null, null, null, 1, 0, 1, 'admin', '2022-09-21 00:24:09', '2022-09-21', 'admin', '2022-10-10 16:16:10');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3511182216329691136, 3509530538144694272, '删除黑白名单', 3, 'deleteBlackOrWhiteRouter', 3, null, null, null, '', 144, null, null, null, 1, 0, 1, 'admin', '2022-09-21 00:24:34', '2022-09-21', 'admin', '2022-10-10 16:15:48');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517851620169744384, 3510991230819368960, '查询字典详情', 3, 'queryDictDetail', 3, null, null, null, '', 150, null, null, null, 1, 0, 1, 'admin', '2022-10-09 10:06:24', '2022-10-09', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517851693284851712, 3510991230819368960, '新增字典', 3, 'addDict', 3, null, null, null, '', 151, null, null, null, 1, 0, 1, 'admin', '2022-10-09 10:06:42', '2022-10-09', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517851756404932608, 3510991230819368960, '编辑字典', 3, 'editDict', 3, null, null, null, '', 152, null, null, null, 1, 0, 1, 'admin', '2022-10-09 10:06:57', '2022-10-09', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517851806027743232, 3510991230819368960, '删除字典', 3, 'deleteDict', 3, null, null, null, '', 153, null, null, null, 1, 0, 1, 'admin', '2022-10-09 10:07:09', '2022-10-09', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517852117849079808, 3510333378140307456, '数据监控', 2, null, 3, 'Sql', 'admin/monitor/sql/index', 'sql', 'sqlMonitor', 23, 1, 0, 0, 1, 0, 1, 'admin', '2022-10-09 10:08:23', '2022-10-09', 'admin', '2022-10-09 10:09:12');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517852698386890752, 3510333378140307456, '服务监控', 2, 'queryServerData', 3, 'Server', 'admin/monitor/server/index', 'server', 'codeConsole', 24, 1, 0, 0, 1, 0, 1, 'admin', '2022-10-09 10:10:41', '2022-10-09', 'admin', '2022-10-09 11:17:06');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517869940738621440, null, '系统运维', 1, null, 3, null, null, 'mnt', 'mnt', 3, null, 0, 0, 1, 0, 1, 'admin', '2022-10-09 11:19:12', '2022-10-09', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3517871036949331968, 3517869940738621440, '接口文档', 2, null, 3, 'Swagger', 'admin/mnt/swagger/index', 'swagger', 'swagger', 31, 0, 1, 0, 0, 0, 1, 'admin', '2022-10-09 11:23:34', '2022-10-09', 'admin', '2022-10-09 18:10:47');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3518226605992312832, 3510991704482119680, '导出操作日志', 3, 'exportOperateLog', 3, null, null, null, '', 210, null, null, null, 1, 0, 1, 'admin', '2022-10-10 10:56:28', '2022-10-10', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3518226751207505920, 3510991881443999744, '导出日志列表', 3, 'exportAllLog', 3, null, null, null, '', 220, null, null, null, 1, 0, 1, 'admin', '2022-10-10 10:57:02', '2022-10-10', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3518226911455084544, 3510991881443999744, '删除日志列表', 3, 'deleteLog', 3, null, null, null, '', 221, null, null, null, 1, 0, 1, 'admin', '2022-10-10 10:57:41', '2022-10-10', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3518227165042704384, 3510991881443999744, '查询日志堆栈详情', 3, 'queryLogErrorDetail', 3, null, null, null, '', 222, null, null, null, 1, 0, 1, 'admin', '2022-10-10 10:58:41', '2022-10-10', '', '');
INSERT INTO permission (ID, PID, PERM_NAME, PERM_TYPE, PERM_CODE, PERM_LEVEL, COMPONENT_NAME, COMPONENT_PATH, ROUTER_PATH, ICON, SORT, CACHE, HIDDEN, I_FRAME, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3518306819808165888, 3509530538144694272, '路由列表查询', 3, 'queryRouterListByPage', 3, null, null, null, '', 140, null, null, null, 1, 0, 1, 'admin', '2022-10-10 16:15:12', '2022-10-10', '', '');

/*Table structure for table `role_permission_relation` */
DROP TABLE IF EXISTS `role_permission_relation`;
CREATE TABLE `role_permission_relation` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ROLE_ID` BIGINT(64) NOT NULL COMMENT '角色编号',
  `PERM_ID` BIGINT(64) NOT NULL COMMENT '权限编号',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_ROLE_PERM` (`ROLE_ID`, `PERM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='角色权限关联表';

/*Table structure for table `router` */
DROP TABLE IF EXISTS `router`;
CREATE TABLE `router` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `NAME` VARCHAR(25) NOT NULL COMMENT '路由名称',
  `CODE` VARCHAR(100) DEFAULT NULL COMMENT '权限编码',
  `DEFAULT_LEVEL` TINYINT(1) NOT NULL DEFAULT 3 COMMENT '路由默认访问级别: 1-公开权限;2-公共权限;3-受控权限',
  `REMARK` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '备注',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='路由表';

/*Table structure for table `interface` */
DROP TABLE IF EXISTS `interface`;
CREATE TABLE `interface` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `CODE` VARCHAR(100) DEFAULT NULL COMMENT '权限编码',
  `URI` VARCHAR(200) NOT NULL COMMENT '路由链接',
  `METHOD` VARCHAR(50) DEFAULT NULL COMMENT '路由请求方式',
  `TYPE` TINYINT(1) NOT NULL COMMENT '接口类型',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_URL_METHOD` (`URI`, `METHOD`),
  INDEX CODE_INDEX (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='接口表';

/*Table structure for table `dict` */
DROP TABLE IF EXISTS `dict`;
CREATE TABLE `dict` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `PID` BIGINT(64) DEFAULT NULL COMMENT 'PID',
  `NAME` VARCHAR(50) NOT NULL COMMENT '字典名称',
  `TYPE` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '类型: 1-组;2-项',
  `KEY` VARCHAR(50) DEFAULT NULL COMMENT '字典KEY',
  `VALUE` TEXT DEFAULT NULL COMMENT '字典VALUE',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序',
  `DESC` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '字典描述',
  `LOCKED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否锁定',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX PID_INDEX (PID),
  INDEX KEY_INDEX (`KEY`),
  INDEX NAME_INDEX (`NAME`),
  INDEX TYPE_INDEX (`TYPE`),
  INDEX ENABLED_INDEX (`ENABLED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='字典表';

/*Data for the table `dict` */
INSERT INTO dict (ID, NAME, `KEY`, VALUE, PID, TYPE, SORT, `DESC`, LOCKED, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, '系统参数', null, null, null, 1, 1, '', 1, 1, 0, 1, 'system', '2021-05-17 01:48:00', '2021-05-17', '', '');
INSERT INTO dict (ID, NAME, `KEY`, VALUE, PID, TYPE, SORT, `DESC`, LOCKED, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (2, '路由白名单', null, null, null, 1, 2, '', 1, 1, 0, 1, 'system', '2021-05-17 01:48:00', '2021-05-17', '', '');
INSERT INTO dict (ID, NAME, `KEY`, VALUE, PID, TYPE, SORT, `DESC`, LOCKED, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3, '路由黑名单', null, null, null, 1, 3, '', 1, 1, 0, 1, 'system', '2021-05-17 01:48:00', '2021-05-17', '', '');

/*Table structure for table `log` */
DROP TABLE IF EXISTS `log`;
CREATE TABLE `log` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `LOG_TYPE` TINYINT(1) NOT NULL COMMENT '日志类型：1-操作日志；2-接口日志；3-异常日志',
  `OPERATE_USER` VARCHAR(50) NOT NULL COMMENT '操作用户',
  `EVENT_TIME` VARCHAR(50) NOT NULL COMMENT '事件发生时间',
  `DESCRIPTION` VARCHAR(50) NOT NULL COMMENT '操作描述',
  `REQUEST_PARAM` TEXT DEFAULT NULL COMMENT '操作参数',
  `REQUEST_IP` VARCHAR(50) DEFAULT NULL COMMENT '请求IP',
  `REQUEST_URI` VARCHAR(200) DEFAULT NULL COMMENT '请求URI',
  `REQUEST_METHOD` VARCHAR(50) DEFAULT NULL COMMENT '请求Method',
  `ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT '请求地址',
  `BROWSER` VARCHAR(200) DEFAULT NULL COMMENT '浏览器',
  `COST_TIME` INT(11) DEFAULT NULL COMMENT '请求耗时',
  `EXEC_RESULT` TINYINT(1) NOT NULL COMMENT '执行结果：0-失败；1-成功',
  `EXEC_MESSAGE` TEXT DEFAULT NULL COMMENT '执行信息',
  `EXCEPTION_DETAIL` TEXT DEFAULT NULL COMMENT '异常信息',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX LOG_TYPE_INDEX (LOG_TYPE),
  INDEX OPERATE_USER_INDEX (OPERATE_USER),
  INDEX EXEC_RESULT_INDEX (EXEC_RESULT)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='日志表';

/*Table structure for table `file` */
DROP TABLE IF EXISTS `file`;
CREATE TABLE `file` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `FILENAME` VARCHAR(250) NOT NULL COMMENT '文件名',
  `ORIGINAL_FILENAME` VARCHAR(250) NOT NULL COMMENT '原文件名称',
  `SIZE` VARCHAR(50) NOT NULL COMMENT '文件大小',
  `FILE_PATH` VARCHAR(1500) NOT NULL DEFAULT '' COMMENT '文件路径',
  `DOWNLOAD_URL` VARCHAR(1500) NOT NULL DEFAULT '' COMMENT '下载链接',
  `MD5` VARCHAR(200) NOT NULL COMMENT '备注',
  `FILE_TYPE` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '文件类型',
  `STORAGE_TYPE` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '存储类型',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文件表';

/*Table structure for table `file_relation` */
DROP TABLE IF EXISTS `file_relation`;
CREATE TABLE `file_relation` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `FILE_ID` BIGINT(64) NOT NULL COMMENT '文件编号',
  `BUSINESS_ID` BIGINT(64) NOT NULL COMMENT '业务编号',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_ROLE_PERM` (`FILE_ID`, `BUSINESS_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文件与业务对象关联表';

/*Table structure for table `user_pass_log` */
DROP TABLE IF EXISTS `user_pass_log`;
CREATE TABLE `user_pass_log` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `USER_ID` BIGINT(64) NOT NULL COMMENT '用户编号',
  `PASSWORD` VARCHAR(60) NOT NULL COMMENT '密码',
  `UPDATE_TIME` VARCHAR(20) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户密码更新日志表';

/*Table structure for table `user_token_storage` */
DROP TABLE IF EXISTS `user_token_storage`;
CREATE TABLE `user_token_storage` (
  `USER_ID` BIGINT(64) NOT NULL COMMENT '用户编号',
  `LASTED_TOKEN` TEXT NOT NULL COMMENT '用户当前的Token',
  `VERSION` INT(11) NOT NULL COMMENT '版本',
  `REMARK` VARCHAR(100) COMMENT '备注',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` VARCHAR(20) COMMENT '更新时间',
  PRIMARY KEY (`USER_ID`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户最新令牌记录表';

/*Table structure for table `log_show_flag` */
DROP TABLE IF EXISTS `log_show_flag`;
CREATE TABLE `log_show_flag` (
  `SHOWED` TINYINT(1) NOT NULL COMMENT '接口日志是否展示',
  `URI` VARCHAR(200) NOT NULL COMMENT '请求地址',
  `METHOD` VARCHAR(50) DEFAULT NULL COMMENT '请求方式',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  INDEX `URI_INDEX` (`URI`),
  INDEX `METHOD_INDEX` (`METHOD`),
  UNIQUE KEY `URI_METHOD_KEY` (`URI`, `METHOD`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='日志展示标识表';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
