/*
SQLyog Community v13.1.7 (64 bit)
MySQL - 5.7.29-log : Database - zblog
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`zblog` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `zblog`;

/*Table structure for table `article_category` */
DROP TABLE IF EXISTS `article_category`;
CREATE TABLE `article_category` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `PID` BIGINT(64) DEFAULT NULL COMMENT '上级类别编号',
  `NAME` VARCHAR(50) NOT NULL COMMENT '类别名称',
  `IMAGE_URL` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '分类预览图',
  `DESC` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '分类描述',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序字段',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_PID` (`PID`),
  KEY `INDEX_KEY_NAME` (`NAME`),
  KEY `INDEX_KEY_ENABLED` (`ENABLED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章分类表';

/*Data for the table `article_category` */
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, null, '技术总结', '', '', 1, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (2, 1, '后端技术', '', '', 10, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3, 1, '前端技术', '', '', 11, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (4, 1, '工具运维', '', '', 12, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (5, 1, '数据库', '', '', 13, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (6, null, '学习笔记', '', '', 2, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (7, 6, '问题记录', '', '', 20, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (8, 6, '源码学习', '', '', 21, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (9, 6, '力扣笔记', '', '', 22, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (10, null, '生活记录', '', '', 3, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (11, 10, '散文随笔', '', '', 31, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');
INSERT INTO article_category (ID, PID, NAME, IMAGE_URL, `DESC`, SORT, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (12, 10, '旅游杂记', '', '', 32, 1, 0, 1, 'admin', '2021-02-28 21:29:11', '2021-02-28', '', '');

/*Table structure for table `article_tag` */
DROP TABLE IF EXISTS `article_tag`;
CREATE TABLE `article_tag` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL COMMENT '标签名称',
  `TYPE` TINYINT(1) NOT NULL COMMENT '标签类型',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_TYPE` (`TYPE`),
  KEY `INDEX_KEY_NAME` (`NAME`),
  KEY `INDEX_KEY_ENABLED` (`ENABLED`),
  KEY `INDEX_KEY_CREATE_USER` (`CREATE_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章标签表';

/*Data for the table `article_tag` */
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, 'Java', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (2, 'Python', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3, 'Shell', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (4, 'Spring', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (5, 'SpringBoot', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (6, 'SpringCloud', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (7, '多线程', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (8, '并发', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (9, '反射', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (10, '集合', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (11, 'JVM', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (12, 'IO', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (13, 'MySQL', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (14, '达梦', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (15, 'Oracle', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (16, 'Redis', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (17, 'AWT', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (18, 'Swing', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (19, 'Linux', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (20, 'Html', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (21, 'Css', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (22, 'JavaScript', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (23, 'Vue', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (24, 'Vue2', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (25, 'Vue3', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (26, 'JQuery', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (27, 'Bootstrap', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (28, 'Tomcat', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (29, 'Echarts', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (30, 'Java关键字', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (31, 'LeeCode', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (32, '算法', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (33, '数据结构', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (34, '数学', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (35, '面试题', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (36, '工具', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (37, '旅游', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (38, '随笔', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (39, '散文', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');
INSERT INTO article_tag (ID, NAME, TYPE, ENABLED, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (40, '笔记', 1, 1, 0, 1, 'admin', '2021-03-01 00:58:53', '2021-03-01', '', '');

/*Table structure for table `article_tag_relation` */
DROP TABLE IF EXISTS `article_tag_relation`;
CREATE TABLE `article_tag_relation` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
  `TAG_ID` BIGINT(64) NOT NULL COMMENT '标签编号',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_ARTICLE_TAG` (`ARTICLE_ID`, `TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章标签关联表';

/*Table structure for table `article` */
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(50) NOT NULL COMMENT '文章标题',
  `REMARK` VARCHAR(250) NOT NULL DEFAULT '' COMMENT '文章概要',
  `CONTENT` TEXT NOT NULL COMMENT '文章内容',
  `CONTENT_MD` TEXT COMMENT '文章内容_Markdown',
  `KEYWORDS` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '文章关键字',
  `COVER_IMAGE` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '文章略缩图',
  `REPRINT_LINK` VARCHAR(1000) DEFAULT NULL COMMENT '原文地址',
  `REPRINT_DESC` VARCHAR(1000) DEFAULT NULL COMMENT '转载说明',
  `ARTICLE_TYPE` INT(2) NOT NULL COMMENT '文章类型',
  `ARTICLE_STATUS` INT(2) NOT NULL COMMENT '文章状态',
  `ARTICLE_PERM` INT(2) NOT NULL COMMENT '文章权限',
  `CATEGORY_ID` BIGINT(64) NOT NULL COMMENT '文章分类',
  `AUTHOR_ID` BIGINT(64) NOT NULL COMMENT '文章作者',
  `COMMENT_FLAG` TINYINT(1) DEFAULT 1 COMMENT '是否允许评论',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_TITLE` (`TITLE`),
  KEY `INDEX_KEY_CATEGORY_ID` (`CATEGORY_ID`),
  KEY `INDEX_KEY_ARTICLE_TYPE` (`ARTICLE_TYPE`),
  KEY `INDEX_KEY_ARTICLE_STATUS` (`ARTICLE_STATUS`),
  KEY `INDEX_KEY_ARTICLE_PERM` (`ARTICLE_PERM`),
  KEY `INDEX_KEY_AUTHOR_ID` (`AUTHOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章表';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
