/*Table structure for table `barrage_message` */
DROP TABLE IF EXISTS `barrage_message`;
CREATE TABLE `barrage_message` (
  `ID` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
  `CONTENT` VARCHAR(500) NOT NULL COMMENT '弹幕内容',
  `USER_ID` BIGINT NULL COMMENT '用户ID（游客为NULL）',
  `NICKNAME` VARCHAR(64) NULL COMMENT '昵称（游客/登录用户）',
  `AVATAR` VARCHAR(255) NULL COMMENT '头像',
  `IP` VARCHAR(64) NOT NULL COMMENT '用户IP',
  `IP_REGION` VARCHAR(128) NULL COMMENT '用户来源',
  `USER_AGENT` VARCHAR(512) NULL COMMENT '浏览器信息',
  `AUDIT_STATUS` TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审 1通过 2拒绝',
  `AUDIT_REASON` VARCHAR(1000) NULL COMMENT '审核拒绝原因',
  `AUDIT_USER_ID` BIGINT NULL COMMENT '审核用户ID',
  `AUDIT_TIME` DATETIME NULL COMMENT '审核时间',
  `DEVICE_ID` VARCHAR(128) NULL COMMENT '设备标识（可选）',
  `SPEED` INT NOT NULL DEFAULT 8 COMMENT '弹幕速度',
  `COLOR` VARCHAR(16) NULL COMMENT '字体颜色',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='弹幕';

/*Table structure for table `category` */
DROP TABLE IF EXISTS `category`;
CREATE TABLE `category` (
  `ID` BIGINT UNSIGNED NOT NULL COMMENT '分类ID',
  `PID` BIGINT UNSIGNED DEFAULT 0 COMMENT '父分类ID，一级为0',
  `NAME` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `SLUG` VARCHAR(100) NOT NULL COMMENT '唯一标识(URL)',
  `IMAGE_URL` VARCHAR(500) COMMENT '分类图',
  `DESCRIPTION` VARCHAR(1000) COMMENT '分类描述',
  `SEO_TITLE` VARCHAR(255) COMMENT 'SEO标题',
  `SEO_KEYWORDS` VARCHAR(255) COMMENT 'SEO关键词',
  `SEO_DESCRIPTION` VARCHAR(500) COMMENT 'SEO描述',
  `ALLOW_INDEX` TINYINT(1) DEFAULT 0 COMMENT '是否允许搜索引擎收录',
  `VISIBLE` TINYINT(1) DEFAULT 1 COMMENT '是否前台展示',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序字段',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `uk_category_slug` (`SLUG`),
  KEY `idx_category_pid` (`PID`),
  KEY `idx_category_sort` (`SORT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章分类表';

/*Table structure for table `tag` */
DROP TABLE IF EXISTS `tag`;
CREATE TABLE `tag` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL COMMENT '标签名称',
  `SLUG` VARCHAR(100) NOT NULL COMMENT '唯一标识(URL)',
  `SEO_TITLE` VARCHAR(255) COMMENT 'SEO标题',
  `SEO_KEYWORDS` VARCHAR(255) COMMENT 'SEO关键词',
  `SEO_DESCRIPTION` VARCHAR(500) COMMENT 'SEO描述',
  `ALLOW_INDEX` TINYINT(1) DEFAULT 0 COMMENT '是否允许搜索引擎收录',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `uk_tag_name` (`NAME`),
  UNIQUE KEY `uk_tag_slug` (`SLUG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章标签表';

/*Data for table `tag` */
INSERT INTO `tag` (`ID`,`NAME`,`SLUG`,`SEO_TITLE`,`SEO_KEYWORDS`,`SEO_DESCRIPTION`,`ALLOW_INDEX`,`ENABLED`,`VERSION`,`CREATE_USER`,`CREATE_TIME`) VALUES
    (1,'Java','java','Java技术文章','Java,后端,编程','Java开发相关技术文章',1,1,1,1,'2026-01-01 10:00:00'),
    (2,'Spring Boot','spring-boot','Spring Boot教程','SpringBoot,Java,框架','Spring Boot开发实战',1,1,1,1,'2026-01-01 10:00:00'),
    (3,'MySQL','mysql','MySQL数据库','MySQL,数据库,SQL','MySQL使用与优化',1,1,1,1,'2026-01-01 10:00:00'),
    (4,'Redis','redis','Redis缓存','Redis,缓存,NoSQL','Redis缓存实战',1,1,1,1,'2026-01-01 10:00:00'),
    (5,'Docker','docker','Docker容器技术','Docker,容器,DevOps','Docker部署与实践',1,1,1,1,'2026-01-01 10:00:00'),
    (6,'Kubernetes','kubernetes','K8s容器编排','Kubernetes,K8s,容器','Kubernetes实战指南',1,1,1,1,'2026-01-01 10:00:00'),
    (7,'Vue','vue','Vue前端框架','Vue,前端,JavaScript','Vue开发指南',1,1,1,1,'2026-01-01 10:00:00'),
    (8,'React','react','React前端框架','React,前端,JS','React开发实践',1,1,1,1,'2026-01-01 10:00:00'),
    (9,'JavaScript','javascript','JavaScript基础','JS,前端,编程','JavaScript深入解析',1,1,1,1,'2026-01-01 10:00:00'),
    (10,'TypeScript','typescript','TypeScript开发','TS,JavaScript,类型系统','TypeScript教程',1,1,1,1,'2026-01-01 10:00:00'),
    (11,'HTML','html','HTML基础','HTML,前端,网页','HTML开发指南',1,1,1,1,'2026-01-01 10:00:00'),
    (12,'CSS','css','CSS样式设计','CSS,前端,样式','CSS布局与优化',1,1,1,1,'2026-01-01 10:00:00'),
    (13,'Node.js','nodejs','Node.js后端开发','Node.js,JavaScript,后端','Node开发指南',1,1,1,1,'2026-01-01 10:00:00'),
    (14,'Nginx','nginx','Nginx配置','Nginx,服务器,反向代理','Nginx实战',1,1,1,1,'2026-01-01 10:00:00'),
    (15,'Linux','linux','Linux系统','Linux,服务器,操作系统','Linux常用命令',1,1,1,1,'2026-01-01 10:00:00'),
    (16,'Git','git','Git版本控制','Git,版本控制,代码管理','Git使用指南',1,1,1,1,'2026-01-01 10:00:00'),
    (17,'算法','algorithm','算法与数据结构','算法,数据结构,编程','算法基础与实战',1,1,1,1,'2026-01-01 10:00:00'),
    (18,'设计模式','design-pattern','设计模式','设计模式,架构,编程','常见设计模式解析',1,1,1,1,'2026-01-01 10:00:00'),
    (19,'微服务','microservices','微服务架构','微服务,架构,SpringCloud','微服务架构实践',1,1,1,1,'2026-01-01 10:00:00'),
    (20,'Spring Cloud','spring-cloud','Spring Cloud教程','SpringCloud,微服务,Java','Spring Cloud开发指南',1,1,1,1,'2026-01-01 10:00:00'),
    (21,'消息队列','mq','消息队列技术','MQ,RabbitMQ,Kafka','消息队列使用',1,1,1,1,'2026-01-01 10:00:00'),
    (22,'Kafka','kafka','Kafka消息队列','Kafka,消息队列,大数据','Kafka实战',1,1,1,1,'2026-01-01 10:00:00'),
    (23,'RabbitMQ','rabbitmq','RabbitMQ消息队列','RabbitMQ,MQ,消息队列','RabbitMQ入门',1,1,1,1,'2026-01-01 10:00:00'),
    (24,'Elasticsearch','elasticsearch','ES搜索引擎','ES,搜索引擎,大数据','Elasticsearch教程',1,1,1,1,'2026-01-01 10:00:00'),
    (25,'日志','log','日志系统','日志,Logback,ELK','日志系统设计',1,1,1,1,'2026-01-01 10:00:00'),
    (26,'安全','security','系统安全','安全,加密,认证','系统安全实践',1,1,1,1,'2026-01-01 10:00:00'),
    (27,'性能优化','performance','性能优化','性能优化,调优','系统性能优化技巧',1,1,1,1,'2026-01-01 10:00:00'),
    (28,'分布式','distributed','分布式系统','分布式,架构','分布式系统设计',1,1,1,1,'2026-01-01 10:00:00'),
    (29,'DevOps','devops','DevOps实践','DevOps,CI/CD','DevOps实践指南',1,1,1,1,'2026-01-01 10:00:00'),
    (30,'测试','test','软件测试','测试,单元测试,自动化','软件测试方法',1,1,1,1,'2026-01-01 10:00:00');

-- article

/*Table structure for table `article_tag_relation` */
DROP TABLE IF EXISTS `article_tag_relation`;
CREATE TABLE `article_tag_relation` (
  `ARTICLE_ID` BIGINT NOT NULL COMMENT '文章编号',
  `TAG_ID` BIGINT NOT NULL COMMENT '标签编号',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除'
) ENGINE=INNODB ROW_FORMAT=DYNAMIC COMMENT='文章标签关联表';

CREATE INDEX idx_atr_article_del_tag ON article_tag_relation (`ARTICLE_ID`, `DELETED`, `TAG_ID`);
CREATE INDEX idx_atr_tag_del_article ON article_tag_relation (`TAG_ID`, `DELETED`, `ARTICLE_ID`);

/*Table structure for table `article` */
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `TITLE` VARCHAR(150) NOT NULL COMMENT '文章标题',
  `SLUG` VARCHAR(150) NOT NULL COMMENT 'URL标识',
  `SUMMARY` VARCHAR(250) COMMENT '文章概要',
  `CONTENT_MD` MEDIUMTEXT NOT NULL COMMENT '文章内容（Markdown）',
  `CONTENT_HTML` MEDIUMTEXT COMMENT '文章内容（HTML）',
  `CATEGORY_ID` BIGINT NOT NULL COMMENT '分类ID',
  `AUTHOR_ID` BIGINT NOT NULL COMMENT '作者ID',
  `SEO_TITLE` VARCHAR(255) COMMENT 'SEO标题',
  `SEO_KEYWORDS` VARCHAR(255) COMMENT 'SEO关键词',
  `SEO_DESCRIPTION` VARCHAR(500) COMMENT 'SEO描述',
  `ARTICLE_TYPE` TINYINT(2) NOT NULL COMMENT '文章类型: 1-原创；2-转载；3-翻译',
  `ARTICLE_STATUS` TINYINT(2) NOT NULL COMMENT '文章状态：1-草稿；2-待审核；3-待审核（定时发布）；4-待发布；5-审核不通过；6：已发布；7-临时下线；8-待整改；9-回收站；99-已删除',
  `ARTICLE_PERM` TINYINT(2) NOT NULL COMMENT '文章权限：1-公开；2-私密；3-密码',
  `PASSWORD` VARCHAR(200) COMMENT '访问密码',
  `REPRINT_LINK` VARCHAR(1000) COMMENT '原文地址',
  `REPRINT_DESC` VARCHAR(500) COMMENT '转载说明',
  `COMMENT_FLAG` TINYINT(1) DEFAULT 0 COMMENT '是否允许评论',
  `TOP_FLAG` TINYINT(1) DEFAULT 0 COMMENT '是否置顶',
  `RECOMMEND_FLAG` TINYINT(1) DEFAULT 0 COMMENT '是否推荐',
  `COVER_IMAGE_TYPE` TINYINT DEFAULT 0 COMMENT '封面类型：1-单封面；2-多封面（轮询）；3-默认；4-文章标题；5-无封面；6-多封面（随机）',
  `WORDS_COUNT` INT NOT NULL COMMENT '总字数',
  `VIEW_COUNT` INT DEFAULT 0 COMMENT '总浏览数',
  `LIKE_COUNT` INT DEFAULT 0 COMMENT '总点赞数',
  `COMMENT_COUNT` INT DEFAULT 0 COMMENT '总评论数',
  `FAVORITE_COUNT` INT DEFAULT 0 COMMENT '总收藏数',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '文章创建时间',
  `PUBLISH_TIME` DATETIME COMMENT '文章发布时间',
  `UPDATE_TIME` DATETIME COMMENT '文章更新时间',
  `DELETE_TIME` DATETIME COMMENT '文章下线时间',
  `VERSION` INT DEFAULT 1 COMMENT '迭代版本',
  `EXTRA_INFO` JSON DEFAULT NULL COMMENT '扩展字段',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `uk_article_slug` (`SLUG`),
  KEY `idx_article_category_id` (`CATEGORY_ID`),
  KEY `idx_article_type` (`ARTICLE_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='文章表';

-- 对 TITLE 和 CONTENT_MD 建立全文索引
ALTER TABLE article ADD FULLTEXT INDEX idx_fulltext_article_title_content (`TITLE`, `CONTENT_HTML`);
CREATE INDEX idx_article_author_status_perm ON article (AUTHOR_ID, ARTICLE_STATUS, ARTICLE_PERM);






/*Table structure for table `article_img_relation` */
DROP TABLE IF EXISTS `article_img_relation`;
CREATE TABLE `article_img_relation` (
  `ARTICLE_ID` BIGINT NOT NULL COMMENT '文章编号',
  `FILE_ID` BIGINT NOT NULL COMMENT '文件编号',
  UNIQUE KEY `KEY_ARTICLE_TAG` (`ARTICLE_ID`, `FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章封面关联表';

/*Table structure for table `article_content_draft_record` */
DROP TABLE IF EXISTS `article_content_draft_record`;
CREATE TABLE `article_content_draft_record` (
`ID` BIGINT(64) UNSIGNED NOT NULL,
`ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
`REMARK` VARCHAR(250) NOT NULL DEFAULT '' COMMENT '文章概要',
`COUNT` VARCHAR(200) DEFAULT NULL COMMENT '文章字数',
`CONTENT` TEXT NOT NULL COMMENT '文章内容: 65535 / 16,777,215',
`SAVE_TIME` VARCHAR(50) NOT NULL COMMENT '自动保存时间',
PRIMARY KEY (`ID`) USING BTREE,
KEY `INDEX_KEY_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章内容草稿记录表';

/*Table structure for table `article_auto_publish_timing` */
DROP TABLE IF EXISTS `article_auto_publish_timing`;
CREATE TABLE `article_auto_publish_timing` (
`ID` BIGINT(64) UNSIGNED NOT NULL,
`ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
`PUBLISH_TIME` VARCHAR(50) NOT NULL COMMENT '消息发布时间: yyyy-MM-dd HH:mm',
`PRODUCER_TIME` VARCHAR(20) NOT NULL COMMENT '消息生产时间: yyyy-MM-dd HH:mm:ss',
`CONSUMER_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '消息消费时间: yyyy-MM-dd HH:mm:ss',
`CONSUMED` TINYINT(1) DEFAULT 0 COMMENT '消息是否被消费',
`VALID` TINYINT(1) DEFAULT 1 COMMENT '消息是否有效',
`DESC` VARCHAR(100) DEFAULT NULL DEFAULT '' COMMENT '备注',
PRIMARY KEY (`ID`) USING BTREE,
KEY `INDEX_KEY_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章自动发布状态记录表';






DROP TABLE IF EXISTS `article_auto_publish_timing`;
CREATE TABLE `article_auto_publish_timing` (
                                               `ID` BIGINT UNSIGNED NOT NULL,
                                               `ARTICLE_ID` BIGINT NOT NULL,

                                               `PUBLISH_TIME` DATETIME NOT NULL,
                                               `STATUS` TINYINT DEFAULT 0 COMMENT '0待发布 1已发布 2失败',

                                               `RETRY_COUNT` INT DEFAULT 0,
                                               `ERROR_MSG` VARCHAR(500),

                                               `CREATE_TIME` DATETIME NOT NULL,
                                               `UPDATE_TIME` DATETIME,

                                               PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时发布';








/*Table structure for table `article_column` */
DROP TABLE IF EXISTS `article_column`;
CREATE TABLE `article_column` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL COMMENT '专栏名称',
  `IMAGE_URL` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '专栏预览图',
  `DESC` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '专栏描述',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序字段',
  `PAGE_SHOW` TINYINT(1) DEFAULT 0 COMMENT '是否首页展示',
  `ENABLED` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_NAME` (`NAME`),
  KEY `INDEX_KEY_PAGE_SHOW` (`PAGE_SHOW`),
  KEY `INDEX_KEY_ENABLED` (`ENABLED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章专栏表';

/*Table structure for table `article_column_relation` */
DROP TABLE IF EXISTS `article_column_relation`;
CREATE TABLE `article_column_relation` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `COLUMN_ID` BIGINT(64) NOT NULL COMMENT '专栏编号',
  `ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
  `ARTICLE_TITLE` VARCHAR(100) NOT NULL COMMENT '文章标题',
  `SORT` INT(11) NOT NULL DEFAULT 99999 COMMENT '排序字段',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_ARTICLE_COLUMN` (`ARTICLE_ID`, `COLUMN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章专栏关联表';


/*Table structure for table `article` */
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(100) NOT NULL COMMENT '文章标题',
  `REMARK` VARCHAR(250) NOT NULL DEFAULT '' COMMENT '文章概要',
  `CONTENT` TEXT NOT NULL COMMENT '文章内容: 65535 / 16,777,215',
  `CONTENT_MD` TEXT COMMENT '文章内容_Markdown',
  `KEYWORDS` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '文章关键字',
  `REPRINT_LINK` VARCHAR(1000) DEFAULT NULL COMMENT '原文地址',
  `REPRINT_DESC` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '转载说明',
  `COVER_IMAGE_TYPE` INT(2) NOT NULL COMMENT '封面类型',
  `ARTICLE_TYPE` INT(2) NOT NULL COMMENT '文章类型',
  `ARTICLE_STATUS` INT(2) DEFAULT NULL COMMENT '文章状态',
  `ARTICLE_PERM` INT(2) DEFAULT NULL COMMENT '文章权限',
  `CATEGORY_ID` BIGINT(64) DEFAULT NULL COMMENT '文章分类',
  `AUTHOR_ID` BIGINT(64) NOT NULL COMMENT '文章作者',
  `COMMENT_FLAG` TINYINT(1) DEFAULT 1 COMMENT '是否允许评论',
  `DESC` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '其他信息',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  `EXTEND1` VARCHAR(200) DEFAULT NULL COMMENT '扩展字段一：编辑器类型：1-WangEditor; 2-Markdown',
  `EXTEND2` VARCHAR(200) DEFAULT NULL COMMENT '扩展字段二：文章字数',
  `EXTEND3` VARCHAR(200) DEFAULT NULL COMMENT '扩展字段三',
  `EXTEND4` VARCHAR(200) DEFAULT NULL COMMENT '扩展字段四',
  `EXTEND5` VARCHAR(200) DEFAULT NULL COMMENT '扩展字段五',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_TITLE` (`TITLE`),
  KEY `INDEX_KEY_CATEGORY_ID` (`CATEGORY_ID`),
  KEY `INDEX_KEY_ARTICLE_TYPE` (`ARTICLE_TYPE`),
  KEY `INDEX_KEY_ARTICLE_STATUS` (`ARTICLE_STATUS`),
  KEY `INDEX_KEY_ARTICLE_PERM` (`ARTICLE_PERM`),
  KEY `INDEX_KEY_AUTHOR_ID` (`AUTHOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章表';

/*Table structure for table `article_content_draft_record` */
DROP TABLE IF EXISTS `article_content_draft_record`;
CREATE TABLE `article_content_draft_record` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
  `REMARK` VARCHAR(250) NOT NULL DEFAULT '' COMMENT '文章概要',
  `COUNT` VARCHAR(200) DEFAULT NULL COMMENT '文章字数',
  `CONTENT` TEXT NOT NULL COMMENT '文章内容: 65535 / 16,777,215',
  `SAVE_TIME` VARCHAR(50) NOT NULL COMMENT '自动保存时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章内容草稿记录表';

/*Table structure for table `article_auto_publish_timing` */
DROP TABLE IF EXISTS `article_auto_publish_timing`;
CREATE TABLE `article_auto_publish_timing` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
  `PUBLISH_TIME` VARCHAR(50) NOT NULL COMMENT '消息发布时间: yyyy-MM-dd HH:mm',
  `PRODUCER_TIME` VARCHAR(20) NOT NULL COMMENT '消息生产时间: yyyy-MM-dd HH:mm:ss',
  `CONSUMER_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '消息消费时间: yyyy-MM-dd HH:mm:ss',
  `CONSUMED` TINYINT(1) DEFAULT 0 COMMENT '消息是否被消费',
  `VALID` TINYINT(1) DEFAULT 1 COMMENT '消息是否有效',
  `DESC` VARCHAR(100) DEFAULT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_ARTICLE_ID` (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章自动发布状态记录表';

/*Table structure for table `website_config` */
DROP TABLE IF EXISTS `website_config`;
CREATE TABLE `website_config` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL COMMENT '配置名称',
  `CONFIG` TEXT NOT NULL COMMENT '配置信息',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='网站配置信息表';

/*Data for the table `website_config` */
INSERT INTO website_config (ID, NAME, CONFIG, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (1, '网站信息', '{"socialLoginList":[],"websiteAdminLink":"https://admin.suntaoblog.com","websiteAuthor":"恋长安兮","websiteAvatar":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/17/3565220826456260608.png","websiteCreateTime":"2021-03-21","websiteIntro":"大浪淘沙，荣辱不惊。","websiteLink":"https://www.suntaoblog.com","websiteName":"孙涛个人博客","websiteNotice":"博客问题交流群：760210629\\n仓库地址：https://github.com/stazxr/zblog\\n相关文档：建设中\\n当前进展：页面优化中，数据迁移中","websiteRecordNo":"陕ICP备2021003044号-1"}', 17, 'admin', '2022-12-08 17:06:00', '2022-12-08', '', '');
INSERT INTO website_config (ID, NAME, CONFIG, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (2, '社交信息', '{"csdn":"","gitee":"","github":"","qq":"","weChat":""}', 16, 'admin', '2022-12-08 17:06:00', '2022-12-08', '', '');
INSERT INTO website_config (ID, NAME, CONFIG, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3, '其他设置', '{"alipayQrCode":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/17/3565221664612417536.jpg","articleCover":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/18/3565734577953570816.jpg","articleSearchStrategy":"mysql","articleViewInterval":0,"isCommentReview":1,"isEmailNotice":0,"isMessageReview":1,"isMusicPlayer":1,"isReward":1,"touristAvatar":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/17/3565221129431810048.png","userAvatar":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/17/3565220996363321344.png","weiXinQrCode":"https://suntaoblog.oss-cn-beijing.aliyuncs.com/upload/2023-02/17/3565221645289259008.jpg"}', 18, 'admin', '2022-12-08 17:06:00', '2022-12-08', '', '');

/*Table structure for table `visitor` */
DROP TABLE IF EXISTS `visitor`;
CREATE TABLE `visitor` (
  `ID` VARCHAR(32) NOT NULL,
  `ADDRESS_IP` VARCHAR(50) NOT NULL COMMENT '访问地址',
  `OS_NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '操作系统',
  `BROWSER_NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '浏览器名称',
  `PROVINCE` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '省份',
  `AREA_CODE` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '地域编码',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='访客表';

/*Table structure for table `visitor_area` */
DROP TABLE IF EXISTS `visitor_area`;
CREATE TABLE `visitor_area` (
  `AREA` VARCHAR(50) NOT NULL COMMENT '访问地域',
  `AREA_COUNT` INT(11) NOT NULL DEFAULT 1 COMMENT '访问量',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  UNIQUE KEY `KEY_AREA` (`AREA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='访客地域表';

/*Table structure for table `visitor_count` */
DROP TABLE IF EXISTS `visitor_count`;
CREATE TABLE `visitor_count` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `WEB_COUNT` INT(11) NOT NULL DEFAULT 1 COMMENT '访问量',
  `DATA_DATE` VARCHAR(20) COMMENT '数据日期: YYYY-MM-DD',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_DATA_DATE` (`DATA_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='访客数统计表';

/*Data for the table `visitor_count` */
INSERT INTO visitor_count (ID, WEB_COUNT, DATA_DATE) VALUES (1, 0, NULL);

/*Table structure for table `talk` */
DROP TABLE IF EXISTS `talk`;
CREATE TABLE `talk` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `CONTENT` TEXT NOT NULL COMMENT '说说内容',
  `IMAGES` TEXT COMMENT '图片列表',
  `STATUS` INT(2) NOT NULL COMMENT '说说状态',
  `IS_TOP` TINYINT(1) DEFAULT 0 COMMENT '是否置顶',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `INDEX_KEY_IS_TOP` (`IS_TOP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='说说';

/*Data for the table `talk` */
INSERT INTO talk (ID, CONTENT, IMAGES, STATUS, IS_TOP, DELETED, VERSION, CREATE_USER, CREATE_TIME, CREATE_DATE, UPDATE_USER, UPDATE_TIME) VALUES (3550278505713369088, '声明：博客框架为SpringBoot2.5 + Vue2，大家有Bug和优化提议欢迎提Issue，也可以加入QQ群（760210629）进行交流。项目前端借鉴了《风、宇个人博客》和《ELADMIN》两个开源项目的内容，感谢两个项目的作者！<img src="https://suntaoblog.oss-cn-beijing.aliyuncs.com/emoji/dacall.jpg" width="24" height="24" alt="[打call]" style="margin: 0 1px; vertical-align: text-bottom">', '', 1, 1, 0, 1, 'admin', '2023-01-06 21:39:16', '2023-01-06', 'admin', '2023-01-06 22:11:01');

/*Table structure for table `album` */
DROP TABLE IF EXISTS `album`;
CREATE TABLE `album` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ALBUM_NAME` VARCHAR(20) NOT NULL COMMENT '相册名称',
  `ALBUM_DESC` VARCHAR(50) NOT NULL COMMENT '相册描述',
  `ALBUM_COVER` VARCHAR(500) NOT NULL COMMENT '相册封面',
  `STATUS` INT(2) NOT NULL COMMENT '相册状态',
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `KEY_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='相册';

/*Table structure for table `album_photo` */
DROP TABLE IF EXISTS `album_photo`;
CREATE TABLE `album_photo` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ALBUM_ID` BIGINT(64) NOT NULL COMMENT '所属相册',
  `FILE_ID` BIGINT(64) NOT NULL COMMENT '图片ID',
  `PHOTO_NAME` VARCHAR(25) NOT NULL COMMENT '照片名称',
  `PHOTO_DESC` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '照片描述',
  `PHOTO_LINK` VARCHAR(500) NOT NULL COMMENT '照片地址',
  `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `KEY_DELETED` (`IS_DELETED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='照片';








/*Table structure for table `talk_like` */
DROP TABLE IF EXISTS `talk_like`;
CREATE TABLE `talk_like` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `USER_ID` BIGINT(64) NOT NULL COMMENT '点赞用户',
  `TALK_ID` BIGINT(64) NULL DEFAULT NULL COMMENT '点赞说说',
  `IP_ADDRESS` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '点赞用户IP',
  `IP_SOURCE` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '点赞用户来源',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_USER_ID_TALK_ID` (`USER_ID`, `TALK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='说说点赞信息';

/*Table structure for table `article_like` */
DROP TABLE IF EXISTS `article_like`;
CREATE TABLE `article_like` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `USER_ID` BIGINT(64) NOT NULL COMMENT '点赞用户',
  `ARTICLE_ID` BIGINT(64) NULL DEFAULT NULL COMMENT '点赞文章',
  `IP_ADDRESS` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '点赞用户IP',
  `IP_SOURCE` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '点赞用户来源',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `KEY_USER_ID_ARTICLE_ID` (`USER_ID`, `ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章点赞记录';

/*Table structure for table `article_view` */
DROP TABLE IF EXISTS `article_view`;
CREATE TABLE `article_view` (
  `ID` BIGINT(64) UNSIGNED NOT NULL,
  `ARTICLE_ID` BIGINT(64) NOT NULL COMMENT '文章编号',
  `ACCESS_IP` VARCHAR(200) NOT NULL COMMENT '访问IP',
  `ACCESS_ADDRESS` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '访问地址',
  `ACCESS_TIME` VARCHAR(50) NOT NULL COMMENT '访问时间',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` VARCHAR(20) NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `CREATE_DATE` VARCHAR(20) NOT NULL COMMENT '创建日期',
  `UPDATE_USER` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章浏览记录';

/*Table structure for table `comment` */
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `USER_ID` BIGINT NOT NULL COMMENT '评论用户',
  `PARENT_ID` BIGINT DEFAULT 0 COMMENT '父评论ID（0=一级评论）',
  `OBJECT_ID` BIGINT NOT NULL COMMENT '评论对象ID',
  `TYPE` TINYINT NOT NULL COMMENT '评论类型',
  `CONTENT` TEXT NOT NULL COMMENT '评论内容',
  `LIKE_COUNT` INT DEFAULT 0 COMMENT '点赞数',
  `REPLY_COUNT` INT DEFAULT 0 COMMENT '回复数',
  `IP_ADDRESS` VARCHAR(45) DEFAULT NULL COMMENT '评论用户IP',
  `IP_SOURCE` VARCHAR(100) DEFAULT NULL COMMENT '评论用户来源',
  `STATUS` TINYINT NOT NULL DEFAULT 0 COMMENT '状态（0待审核 1正常 2拒绝 3删除）',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `idx_comment_object_id_type` (`OBJECT_ID`, `TYPE`),
  KEY `idx_comment_parent_id` (`PARENT_ID`),
  KEY `idx_comment_user_id` (`USER_ID`),
  KEY `idx_comment_create_time` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评论表';

DROP TABLE IF EXISTS `comment_like`;
CREATE TABLE `comment_like` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `USER_ID` BIGINT NOT NULL COMMENT '点赞用户',
  `COMMENT_ID` BIGINT NOT NULL COMMENT '评论ID',
  `IP_ADDRESS` VARCHAR(45) DEFAULT NULL COMMENT 'IP地址',
  `IP_SOURCE` VARCHAR(100) DEFAULT NULL COMMENT 'IP来源',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_comment_like_user_comment` (`USER_ID`, `COMMENT_ID`),
  KEY `idx_comment_like_comment_id` (`COMMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='评论点赞表';

/*Table structure for table `friend_link` */
DROP TABLE IF EXISTS `friend_link`;
CREATE TABLE `friend_link` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL COMMENT '网站名称',
  `URL` VARCHAR(255) NOT NULL COMMENT '网站地址',
  `LOGO` VARCHAR(255) DEFAULT NULL COMMENT '网站Logo',
  `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '网站描述',
  `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '申请人邮箱',
  `CONTACT` VARCHAR(100) DEFAULT NULL COMMENT '联系方式',
  `STATUS` TINYINT(1) DEFAULT 0 COMMENT '审批状态：0待审核 1通过 2拒绝',
  `IS_VISIBLE` TINYINT(1) DEFAULT 1 COMMENT '是否展示',
  `ALLOW_FOLLOW` TINYINT(1) DEFAULT 0 COMMENT '是否允许传递SEO权重',
  `SORT` INT DEFAULT 0 COMMENT '排序值（越大越靠前）',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `idx_friend_link_status` (`STATUS`),
  KEY `idx_friend_link_sort` (`SORT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='友链表';

DROP TABLE IF EXISTS `friend_link_stat`;
CREATE TABLE `friend_link_stat` (
  `LINK_ID` BIGINT NOT NULL COMMENT '友链ID',
  `CLICK_COUNT` BIGINT DEFAULT 0 COMMENT '总点击数',
  `DAY_CLICK` INT DEFAULT 0 COMMENT '今日点击',
  `WEEK_CLICK` INT DEFAULT 0 COMMENT '本周点击',
  `MONTH_CLICK` INT DEFAULT 0 COMMENT '本月点击',
  `LAST_CLICK_TIME` DATETIME DEFAULT NULL,
  PRIMARY KEY (`LINK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='友链统计表';

CREATE TABLE `friend_link_click_log` (
  `LINK_ID` BIGINT NOT NULL COMMENT '友链ID',
  `IP` VARCHAR(50) COMMENT '访问IP',
  `USER_AGENT` VARCHAR(255) COMMENT '用户代理',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '访问时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='友链访问记录表';
