DROP TABLE IF EXISTS `i18n_message`;
CREATE TABLE `i18n_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `code` VARCHAR(255) NOT NULL COMMENT '消息代码，建议带前缀标识类别',
  `locale` VARCHAR(20) NOT NULL COMMENT '语言标识，如 zh_CN、en_US',
  `message` VARCHAR(500) NOT NULL COMMENT '国际化文本内容',
  `type` VARCHAR(100) NOT NULL COMMENT '消息类型',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_locale` (`code`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='国际化消息表';

INSERT INTO `i18n_message` (`code`, `locale`, `message`, `type`) VALUES
-- 返回相关
('result.failed', 'zh_CN', '操作失败', 'common'),
('result.failed', 'en_US', 'The operation was failed', 'common'),
('result.success', 'zh_CN', '操作成功', 'common'),
('result.success', 'en_US', 'The operation was successful', 'common'),
('result.param.valid.failed', 'zh_CN', '参数校验失败', 'common'),
('result.param.valid.failed', 'en_US', 'Param validation failed, Please check and try again', 'common'),
('result.data.valid.failed', 'zh_CN', '数据校验失败', 'common'),
('result.data.valid.failed', 'en_US', 'Data validation failed, Please check and try again', 'common'),
('result.request.param.bind.failed', 'zh_CN', '请求参数绑定失败，请检查上送参数', 'common'),
('result.request.param.bind.failed', 'en_US', 'Request parameter binding failed, please check your param', 'common'),
('result.perm.add.failed', 'zh_CN', '权限新增失败', 'common'),
('result.perm.add.failed', 'en_US', 'Failed to add permission', 'common'),
('result.perm.edit.failed', 'zh_CN', '权限修改失败', 'common'),
('result.perm.edit.failed', 'en_US', 'Failed to update permission', 'common'),
('result.perm.delete.failed', 'zh_CN', '权限删除失败', 'common'),
('result.perm.delete.failed', 'en_US', 'Failed to delete permission', 'common'),
('result.role.add.failed', 'zh_CN', '角色新增失败', 'common'),
('result.role.add.failed', 'en_US', 'Failed to add role', 'common'),
('result.role.edit.failed', 'zh_CN', '角色修改失败', 'common'),
('result.role.edit.failed', 'en_US', 'Failed to update role', 'common'),
('result.role.delete.failed', 'zh_CN', '角色删除失败', 'common'),
('result.role.delete.failed', 'en_US', 'Failed to delete role', 'common'),
('result.user.add.failed', 'zh_CN', '用户新增失败', 'common'),
('result.user.add.failed', 'en_US', 'Failed to add user', 'common'),
('result.user.edit.failed', 'zh_CN', '用户修改失败', 'common'),
('result.user.edit.failed', 'en_US', 'Failed to update user', 'common'),
('result.user.delete.failed', 'zh_CN', '用户删除失败', 'common'),
('result.user.delete.failed', 'en_US', 'Failed to delete user', 'common'),
('result.dict.add.failed', 'zh_CN', '字典新增失败', 'common'),
('result.dict.add.failed', 'en_US', 'Failed to add dict', 'common'),
('result.dict.edit.failed', 'zh_CN', '字典修改失败', 'common'),
('result.dict.edit.failed', 'en_US', 'Failed to update dict', 'common'),
('result.dict.delete.failed', 'zh_CN', '字典删除失败', 'common'),
('result.dict.delete.failed', 'en_US', 'Failed to delete dict', 'common'),

-- 校验相关
('valid.comm.param.NotNull', 'zh_CN', '参数不能为空', 'common'),
('valid.comm.param.NotNull', 'en_US', 'Parameter cannot be null', 'common'),
('valid.comm.param.NotBlank', 'zh_CN', '参数不能为空或仅包含空白字符', 'common'),
('valid.comm.param.NotBlank', 'en_US', 'Parameter cannot be blank or whitespace only', 'common'),
('valid.common.page.NotNull', 'zh_CN', '分页页码不能为空', 'common'),
('valid.common.page.NotNull', 'en_US', 'Page number cannot be null', 'common'),
('valid.common.pageSize.NotNull', 'zh_CN', '分页大小不能为空', 'common'),
('valid.common.pageSize.NotNull', 'en_US', 'Page size cannot be null', 'common'),
('valid.perm.id.NotNull', 'zh_CN', '权限ID不能为空', 'common'),
('valid.perm.id.NotNull', 'en_US', 'Permission ID cannot be null', 'common'),
('valid.perm.name.NotBlank', 'zh_CN', '权限名称不能为空', 'common'),
('valid.perm.name.NotBlank', 'en_US', 'Permission name cannot be blank', 'common'),
('valid.perm.type.NotNull', 'zh_CN', '权限类型不能为空', 'common'),
('valid.perm.type.NotNull', 'en_US', 'Permission type cannot be null', 'common'),
('valid.perm.level.NotNull', 'zh_CN', '权限等级不能为空', 'common'),
('valid.perm.level.NotNull', 'en_US', 'Permission level cannot be null', 'common'),
('valid.perm.sort.NotNull', 'zh_CN', '权限排序值不能为空', 'common'),
('valid.perm.sort.NotNull', 'en_US', 'Permission sort cannot be null', 'common'),
('valid.perm.enabled.NotNull', 'zh_CN', '权限是否启用不能为空', 'common'),
('valid.perm.enabled.NotNull', 'en_US', 'Permission enabled cannot be null', 'common'),
('valid.perm.hidden.NotNull', 'zh_CN', '菜单可见不能为空', 'common'),
('valid.perm.hidden.NotNull', 'en_US', 'Permission hidden cannot be null', 'common'),
('valid.perm.cacheable.NotNull', 'zh_CN', '菜单缓存不能为空', 'common'),
('valid.perm.cacheable.NotNull', 'en_US', 'Permission cacheable cannot be null', 'common'),
('valid.perm.routerPath.NotBlank', 'zh_CN', '权限路由地址不能为空', 'common'),
('valid.perm.routerPath.NotBlank', 'en_US', 'Permission routerPath cannot be blank', 'common'),
('valid.perm.routerPath.patternError', 'zh_CN', '路由地址格式不正确', 'common'),
('valid.perm.routerPath.patternError', 'en_US', 'Permission routerPath pattern invalid', 'common'),
('valid.perm.routerPath.exist', 'zh_CN', '路由地址已经存在', 'common'),
('valid.perm.routerPath.exist', 'en_US', 'Permission routerPath exist', 'common'),
('valid.perm.linkPath.NotBlank', 'zh_CN', '权限外链地址不能为空', 'common'),
('valid.perm.linkPath.NotBlank', 'en_US', 'Permission linkPath cannot be blank', 'common'),
('valid.perm.linkPath.patternError', 'zh_CN', '外链地址格式不正确', 'common'),
('valid.perm.linkPath.patternError', 'en_US', 'Permission linkPath pattern invalid', 'common'),
('valid.perm.permCode.NotBlank', 'zh_CN', '权限编码不能为空', 'common'),
('valid.perm.permCode.NotBlank', 'en_US', 'Permission permCode cannot be blank', 'common'),
('valid.perm.permCode.exist', 'zh_CN', '权限编码已经存在', 'common'),
('valid.perm.permCode.exist', 'en_US', 'Permission permCode exist', 'common'),
('valid.perm.componentName.NotBlank', 'zh_CN', '权限组件名称不能为空', 'common'),
('valid.perm.componentName.NotBlank', 'en_US', 'Permission componentName cannot be blank', 'common'),
('valid.perm.componentPath.NotBlank', 'zh_CN', '权限组件路径不能为空', 'common'),
('valid.perm.componentPath.NotBlank', 'en_US', 'Permission componentPath cannot be blank', 'common'),
('valid.perm.dir.parentError', 'zh_CN', '目录的上级只能是目录', 'common'),
('valid.perm.dir.parentError', 'en_US', 'Invalid parent directory setting of Dir', 'common'),
('valid.perm.link.parentError', 'zh_CN', '外链的上级只能是目录', 'common'),
('valid.perm.link.parentError', 'en_US', 'Invalid parent directory setting of Link', 'common'),
('valid.perm.menu.parentError', 'zh_CN', '菜单的上级只能是目录', 'common'),
('valid.perm.menu.parentError', 'en_US', 'Invalid parent directory setting of Menu', 'common'),
('valid.perm.btn.parentError', 'zh_CN', '按钮的上级只能是目录或菜单', 'common'),
('valid.perm.btn.parentError', 'en_US', 'Invalid parent directory setting of Btn', 'common'),
('valid.perm.add.idIsNull', 'zh_CN', '权限新增参数异常，请刷新页面重试', 'common'),
('valid.perm.add.idIsNull', 'en_US', 'Permission parameter error, please refresh the page and try again', 'common'),
('valid.perm.not.exist', 'zh_CN', '权限不存在，请刷新页面后重试', 'common'),
('valid.perm.not.exist', 'en_US', 'Permission does not exist, please refresh the page and try again', 'common'),
('valid.perm.parent.notExist', 'zh_CN', '上级权限不存在，请刷新页面后重试', 'common'),
('valid.perm.parent.notExist', 'en_US', 'Parent permission does not exist, please refresh the page and try again', 'common'),
('valid.perm.permType.notAllowedEdit', 'zh_CN', '权限类型不允许编辑', 'common'),
('valid.perm.permType.notAllowedEdit', 'en_US', 'Permission permType not allowed edit', 'common'),
('valid.perm.permType.invalid', 'zh_CN', '非法的权限类型：{0}', 'common'),
('valid.perm.permType.invalid', 'en_US', 'Permission permType {0} invalid', 'common'),
('valid.perm.delete.hasChild', 'zh_CN', '待删除权限存在子节点，无法被删除，请先删除子节点', 'common'),
('valid.perm.delete.hasChild', 'en_US', 'Cannot delete the permission because it has child nodes. Please remove the child nodes first.', 'common'),
('valid.role.id.NotNull', 'zh_CN', '角色ID不能为空', 'common'),
('valid.role.id.NotNull', 'en_US', 'Role ID cannot be null', 'common'),
('valid.role.not.exist', 'zh_CN', '角色不存在，请刷新页面后重试', 'common'),
('valid.role.not.exist', 'en_US', 'Role does not exist, please refresh the page and try again', 'common'),
('valid.role.roleName.NotBlank', 'zh_CN', '角色名称不能为空', 'common'),
('valid.role.roleName.NotBlank', 'en_US', 'RoleName cannot be blank', 'common'),
('valid.role.roleCode.NotBlank', 'zh_CN', '角色编码不能为空', 'common'),
('valid.role.roleCode.NotBlank', 'en_US', 'RoleCode cannot be blank', 'common'),
('valid.role.enabled.NotNull', 'zh_CN', '角色状态不能为空', 'common'),
('valid.role.enabled.NotNull', 'en_US', 'Role enabled cannot be null', 'common'),
('valid.role.add.idIsNull', 'zh_CN', '角色新增参数异常，请刷新页面重试', 'common'),
('valid.role.add.idIsNull', 'en_US', 'Role parameter error, please refresh the page and try again', 'common'),
('valid.role.roleName.exist', 'zh_CN', '角色名称已经存在', 'common'),
('valid.role.roleName.exist', 'en_US', 'Role roleName exist', 'common'),
('valid.role.roleCode.patternError', 'zh_CN', '角色编码格式不正确', 'common'),
('valid.role.roleCode.patternError', 'en_US', 'Role roleCode pattern invalid', 'common'),
('valid.role.roleCode.forbid', 'zh_CN', '角色编码被禁止使用，请换一个', 'common'),
('valid.role.roleCode.forbid', 'en_US', 'Role roleCode forbid', 'common'),
('valid.role.roleCode.exist', 'zh_CN', '角色编码已经存在', 'common'),
('valid.role.roleCode.exist', 'en_US', 'Role roleCode exist', 'common'),
('valid.user.id.NotNull', 'zh_CN', '用户ID不能为空', 'common'),
('valid.user.id.NotNull', 'en_US', 'User ID cannot be null', 'common'),
('valid.user.username.NotBlank', 'zh_CN', '用户名不能为空', 'common'),
('valid.user.username.NotBlank', 'en_US', 'User username cannot be blank', 'common'),
('valid.user.email.NotBlank', 'zh_CN', '邮箱不能为空', 'common'),
('valid.user.email.NotBlank', 'en_US', 'User email cannot be blank', 'common'),
('valid.user.userType.NotNull', 'zh_CN', '用户类型不能为空', 'common'),
('valid.user.userType.NotNull', 'en_US', 'User userType cannot be null', 'common'),
('valid.user.userStatus.NotNull', 'zh_CN', '用户状态不能为空', 'common'),
('valid.user.userStatus.NotNull', 'en_US', 'User userStatus cannot be null', 'common'),
('valid.user.add.idIsNull', 'zh_CN', '用户新增参数异常，请刷新页面重试', 'common'),
('valid.user.add.idIsNull', 'en_US', 'User parameter error, please refresh the page and try again', 'common'),
('valid.user.not.exist', 'zh_CN', '用户不存在', 'common'),
('valid.user.not.exist', 'en_US', 'User does not exist', 'common'),
('valid.user.username.exist', 'zh_CN', '用户名已经存在', 'common'),
('valid.user.username.exist', 'en_US', 'User username exist', 'common'),
('valid.user.email.exist', 'zh_CN', '邮箱已经存在', 'common'),
('valid.user.email.exist', 'en_US', 'User email exist', 'common'),
('valid.user.nickname.exist', 'zh_CN', '用户昵称已经存在', 'common'),
('valid.user.nickname.exist', 'en_US', 'User nickname exist', 'common'),
('valid.user.username.patternError', 'zh_CN', '用户名只允许包含数字和字母, 且长度范围要求为[4, 20]', 'common'),
('valid.user.username.patternError', 'en_US', 'User username pattern invalid', 'common'),
('valid.user.email.patternError', 'zh_CN', '邮箱格式不正确', 'common'),
('valid.user.email.patternError', 'en_US', 'User email pattern invalid', 'common'),
('valid.user.expiredTime.NotBlank', 'zh_CN', '临时用户账号有效期不能为空', 'common'),
('valid.user.expiredTime.NotBlank', 'en_US', 'Temp user expiredTime cannot be blank', 'common'),
('valid.user.username.notAllowedEdit', 'zh_CN', '用户名不允许编辑', 'common'),
('valid.user.username.notAllowedEdit', 'en_US', 'User username not allowed edit', 'common'),
('valid.user.forbidDelSelf', 'zh_CN', '无法删除自己', 'common'),
('valid.user.forbidDelSelf', 'en_US', 'User can not delete self', 'common'),
('valid.user.norForbidDelAdmin', 'zh_CN', '普通用户无法删除管理员账号', 'common'),
('valid.user.norForbidDelAdmin', 'en_US', 'Normal user can not delete admin user', 'common'),
('valid.user.norForbidAddAdmin', 'zh_CN', '普通用户无法新增管理员账号', 'common'),
('valid.user.norForbidAddAdmin', 'en_US', 'Normal user can not add admin user', 'common'),
('valid.user.norForbidEditAdmin', 'zh_CN', '普通用户无法修改管理员账号', 'common'),
('valid.user.norForbidEditAdmin', 'en_US', 'Normal user can not edit admin user', 'common'),
('valid.user.forbidDelSuperAdmin', 'zh_CN', '无法修改超级管理员', 'common'),
('valid.user.forbidDelSuperAdmin', 'en_US', 'Forbid delete super admin', 'common'),

-- 错误相关
('error.unauthorized.access', 'zh_CN', '未授权访问', 'common'),
('error.unauthorized.access', 'en_US', 'Unauthorized access', 'common'),

-- 权限相关
('perm.access.denied', 'zh_CN', '访问被拒绝', 'common'),
('perm.access.denied', 'en_US', 'Access Denied', 'common'),

-- 界面相关
('ui.button.save', 'zh_CN', '保存', 'UI'),
('ui.button.save', 'en_US', 'Save', 'UI'),

-- 其他示例
('sys.welcome.message', 'zh_CN', '欢迎使用系统', 'SYSTEM'),
('sys.welcome.message', 'en_US', 'Welcome to the system', 'SYSTEM');
