USE `zblog`;

DROP TABLE IF EXISTS `i18n_message`;
CREATE TABLE `i18n_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `code` VARCHAR(255) NOT NULL COMMENT '消息代码，建议带前缀标识类别',
  `locale` VARCHAR(20) NOT NULL COMMENT '语言标识，如 zh_CN、en_US',
  `message` VARCHAR(500) NOT NULL COMMENT '国际化文本内容',
  `type` VARCHAR(100) NOT NULL COMMENT '消息类型',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_locale` (`code`, `locale`)
) ENGINE=InnoDB COMMENT='国际化消息表';

INSERT INTO `i18n_message` (`code`, `locale`, `message`, `type`) VALUES
-- 返回相关 >-->
('result.failed', 'zh_CN', '操作失败', 'common'),
('result.failed', 'en_US', 'Operation failed', 'common'),
('result.success', 'zh_CN', '操作成功', 'common'),
('result.success', 'en_US', 'Operation successful', 'common'),
('result.common.add.failed', 'zh_CN', '新增失败', 'common'),
('result.common.add.failed', 'en_US', 'Failed to add', 'common'),
('result.common.edit.failed', 'zh_CN', '修改失败', 'common'),
('result.common.edit.failed', 'en_US', 'Failed to update', 'common'),
('result.common.delete.failed', 'zh_CN', '删除失败', 'common'),
('result.common.delete.failed', 'en_US', 'Failed to delete', 'common'),
('result.param.valid.failed', 'zh_CN', '参数校验失败，请检查后重试', 'common'),
('result.param.valid.failed', 'en_US', 'Parameter validation failed. Please check and try again', 'common'),
('result.data.valid.failed', 'zh_CN', '数据校验失败，请检查后重试', 'common'),
('result.data.valid.failed', 'en_US', 'Data validation failed. Please check and try again', 'common'),
('result.request.param.bind.failed', 'zh_CN', '请求参数绑定失败，请检查参数后重试', 'common'),
('result.request.param.bind.failed', 'en_US', 'Request parameter binding failed. Please check the parameters and try again', 'common'),
('result.usercenter.password.failed', 'zh_CN', '密码修改失败', 'common'),
('result.usercenter.password.failed', 'en_US', 'Failed to update password', 'common'),
-- 校验相关 >-->
-- 公共校验
('valid.comm.param.NotNull', 'zh_CN', '参数不能为空', 'common'),
('valid.comm.param.NotNull', 'en_US', 'Parameter cannot be null', 'common'),
('valid.comm.param.NotBlank', 'zh_CN', '参数不能为空或仅包含空白字符', 'common'),
('valid.comm.param.NotBlank', 'en_US', 'Parameter cannot be blank or whitespace only', 'common'),
('valid.common.page.NotNull', 'zh_CN', '分页页码不能为空', 'common'),
('valid.common.page.NotNull', 'en_US', 'Page number cannot be null', 'common'),
('valid.common.pageSize.NotNull', 'zh_CN', '分页大小不能为空', 'common'),
('valid.common.pageSize.NotNull', 'en_US', 'Page size cannot be null', 'common'),
('valid.common.id.NotNull', 'zh_CN', 'ID不能为空', 'common'),
('valid.common.id.NotNull', 'en_US', 'ID cannot be null', 'common'),
('valid.common.sort.NotNull', 'zh_CN', '排序字段不能为空', 'common'),
('valid.common.sort.NotNull', 'en_US', 'Sort field must not be null', 'common'),
('valid.common.sort.Max99999', 'zh_CN', '排序字段最大值为99999', 'common'),
('valid.common.sort.Max99999', 'en_US', 'Sort field must be less than or equal to 99999', 'common'),
('valid.common.sort.Min1', 'zh_CN', '排序字段最小值为1', 'common'),
('valid.common.sort.Min1', 'en_US', 'Sort field must be greater than or equal to 1', 'common'),
('valid.common.data.notFound', 'zh_CN', '数据不存在', 'common'),
('valid.common.data.notFound', 'en_US', 'Data not found', 'common'),
('valid.common.data.deleted', 'zh_CN', '数据已删除', 'common'),
('valid.common.data.deleted', 'en_US', 'Data has been deleted', 'common'),
('valid.common.addWithIdError', 'zh_CN', '参数异常[A001]，请刷新页面后重试', 'common'),
('valid.common.addWithIdError', 'en_US', 'Invalid parameter [A001]. Please refresh the page and try again', 'common'),
-- 用户相关
('valid.user.username.NotBlank', 'zh_CN', '用户名不能为空', 'common'),
('valid.user.username.NotBlank', 'en_US', 'User username cannot be blank', 'common'),
('valid.user.email.NotBlank', 'zh_CN', '邮箱不能为空', 'common'),
('valid.user.email.NotBlank', 'en_US', 'User email cannot be blank', 'common'),
('valid.user.userType.NotNull', 'zh_CN', '用户类型不能为空', 'common'),
('valid.user.userType.NotNull', 'en_US', 'User userType cannot be null', 'common'),
('valid.user.userStatus.NotNull', 'zh_CN', '用户状态不能为空', 'common'),
('valid.user.userStatus.NotNull', 'en_US', 'User userStatus cannot be null', 'common'),
('valid.user.not.exist', 'zh_CN', '用户不存在', 'common'),
('valid.user.not.exist', 'en_US', 'User does not exist', 'common'),
('valid.user.username.exist', 'zh_CN', '用户名已经存在', 'common'),
('valid.user.username.exist', 'en_US', 'User username exist', 'common'),
('valid.user.email.exist', 'zh_CN', '邮箱已经存在', 'common'),
('valid.user.email.exist', 'en_US', 'User email exist', 'common'),
('valid.user.nickname.exist', 'zh_CN', '用户昵称已经存在', 'common'),
('valid.user.nickname.exist', 'en_US', 'User nickname exist', 'common'),
('valid.user.username.patternError', 'zh_CN', '用户名只允许包含数字和字母, 且长度范围要求为[4, 20]', 'common'),
('valid.user.username.patternError', 'en_US', 'User username pattern invalid', 'common'),
('valid.user.email.patternError', 'zh_CN', '邮箱格式不正确', 'common'),
('valid.user.email.patternError', 'en_US', 'User email pattern invalid', 'common'),
('valid.user.expiredTime.NotBlank', 'zh_CN', '临时用户账号有效期不能为空', 'common'),
('valid.user.expiredTime.NotBlank', 'en_US', 'Temp user expiredTime cannot be blank', 'common'),
('valid.user.username.notAllowedEdit', 'zh_CN', '用户名不允许编辑', 'common'),
('valid.user.username.notAllowedEdit', 'en_US', 'User username not allowed edit', 'common'),
('valid.user.forbidDelSelf', 'zh_CN', '无法删除自己', 'common'),
('valid.user.forbidDelSelf', 'en_US', 'User can not delete self', 'common'),
('valid.user.norForbidDelAdmin', 'zh_CN', '普通用户无法删除管理员账号', 'common'),
('valid.user.norForbidDelAdmin', 'en_US', 'Normal user can not delete admin user', 'common'),
('valid.user.norForbidAddAdmin', 'zh_CN', '普通用户无法新增管理员账号', 'common'),
('valid.user.norForbidAddAdmin', 'en_US', 'Normal user can not add admin user', 'common'),
('valid.user.norForbidEditAdmin', 'zh_CN', '普通用户无法修改管理员账号', 'common'),
('valid.user.norForbidEditAdmin', 'en_US', 'Normal user can not edit admin user', 'common'),
('valid.user.forbidDelSuperAdmin', 'zh_CN', '无法修改超级管理员', 'common'),
('valid.user.forbidDelSuperAdmin', 'en_US', 'Forbid delete super admin', 'common'),
-- 用户中心相关
('valid.usercenter.username.NotBlank', 'zh_CN', '用户名不能为空', 'common'),
('valid.usercenter.username.NotBlank', 'en_US', 'Username cannot be blank', 'common'),
('valid.usercenter.oldPass.NotBlank', 'zh_CN', '原密码不能为空', 'common'),
('valid.usercenter.oldPass.NotBlank', 'en_US', 'Current password cannot be blank', 'common'),
('valid.usercenter.newPass.NotBlank', 'zh_CN', '新密码不能为空', 'common'),
('valid.usercenter.newPass.NotBlank', 'en_US', 'New password cannot be blank', 'common'),
('valid.usercenter.confirmPass.NotBlank', 'zh_CN', '确认密码不能为空', 'common'),
('valid.usercenter.confirmPass.NotBlank', 'en_US', 'Confirm password cannot be blank', 'common'),
('valid.usercenter.confirmPass.notMatch', 'zh_CN', '两次输入的新密码不一致', 'common'),
('valid.usercenter.confirmPass.notMatch', 'en_US', 'The new passwords do not match', 'common'),
('valid.usercenter.user.NotExist', 'zh_CN', '用户不存在', 'common'),
('valid.usercenter.user.NotExist', 'en_US', 'User does not exist', 'common'),
('valid.usercenter.oldPass.notMatch', 'zh_CN', '原密码错误', 'common'),
('valid.usercenter.oldPass.notMatch', 'en_US', 'Current password is incorrect', 'common'),
('valid.usercenter.samePassword', 'zh_CN', '新密码与原密码不能相同', 'common'),
('valid.usercenter.samePassword', 'en_US', 'New password cannot be the same as the current password', 'common'),
('valid.usercenter.passwordContainUsername', 'zh_CN', '密码不能包含用户名', 'common'),
('valid.usercenter.passwordContainUsername', 'en_US', 'Password cannot contain the username', 'common'),
('valid.usercenter.passwordSimple', 'zh_CN', '密码长度必须大于等于6位且小于等于20位，需要包含大写字母，小写字母，数字，特殊字符中的至少两种', 'common'),
('valid.usercenter.passwordSimple', 'en_US', 'Password must be 6-20 characters long and include at least two of the following: uppercase letters, lowercase letters, numbers, special characters', 'common'),
('valid.usercenter.matchHistoryPass', 'zh_CN', '新密码不能与最近{0}次密码重复', 'common'),
('valid.usercenter.matchHistoryPass', 'en_US', 'New password cannot be the same as the last {0} passwords', 'common'),
-- 角色相关
('valid.role.roleName.NotBlank', 'zh_CN', '角色名称不能为空', 'common'),
('valid.role.roleName.NotBlank', 'en_US', 'Role name cannot be blank', 'common'),
('valid.role.roleCode.NotBlank', 'zh_CN', '角色编码不能为空', 'common'),
('valid.role.roleCode.NotBlank', 'en_US', 'Role code cannot be blank', 'common'),
('valid.role.enabled.NotNull', 'zh_CN', '角色状态不能为空', 'common'),
('valid.role.enabled.NotNull', 'en_US', 'Role enabled cannot be null', 'common'),
('valid.role.roleName.exist', 'zh_CN', '角色名称已经存在', 'common'),
('valid.role.roleName.exist', 'en_US', 'Role name already exists', 'common'),
('valid.role.roleCode.patternError', 'zh_CN', '角色编码格式不正确', 'common'),
('valid.role.roleCode.patternError', 'en_US', 'Role code is invalid', 'common'),
('valid.role.roleCode.forbid', 'zh_CN', '角色编码被禁止使用，请换一个', 'common'),
('valid.role.roleCode.forbid', 'en_US', 'This role code is not allowed. Please choose another', 'common'),
('valid.role.roleCode.exist', 'zh_CN', '角色编码已经存在', 'common'),
('valid.role.roleCode.exist', 'en_US', 'Role code already exists', 'common'),
-- 权限相关
('valid.perm.name.NotBlank', 'zh_CN', '权限名称不能为空', 'common'),
('valid.perm.name.NotBlank', 'en_US', 'Permission name cannot be blank', 'common'),
('valid.perm.type.NotNull', 'zh_CN', '权限类型不能为空', 'common'),
('valid.perm.type.NotNull', 'en_US', 'Permission type cannot be null', 'common'),
('valid.perm.level.NotNull', 'zh_CN', '权限等级不能为空', 'common'),
('valid.perm.level.NotNull', 'en_US', 'Permission level cannot be null', 'common'),
('valid.perm.enabled.NotNull', 'zh_CN', '权限是否启用不能为空', 'common'),
('valid.perm.enabled.NotNull', 'en_US', 'Permission enabled cannot be null', 'common'),
('valid.perm.hidden.NotNull', 'zh_CN', '菜单可见不能为空', 'common'),
('valid.perm.hidden.NotNull', 'en_US', 'Permission hidden cannot be null', 'common'),
('valid.perm.cacheable.NotNull', 'zh_CN', '菜单缓存不能为空', 'common'),
('valid.perm.cacheable.NotNull', 'en_US', 'Permission cacheable cannot be null', 'common'),
('valid.perm.routerPath.NotBlank', 'zh_CN', '权限路由地址不能为空', 'common'),
('valid.perm.routerPath.NotBlank', 'en_US', 'Permission routerPath cannot be blank', 'common'),
('valid.perm.routerPath.patternError', 'zh_CN', '路由地址格式不正确', 'common'),
('valid.perm.routerPath.patternError', 'en_US', 'Permission routerPath is invalid', 'common'),
('valid.perm.routerPath.exist', 'zh_CN', '路由地址已经存在', 'common'),
('valid.perm.routerPath.exist', 'en_US', 'Permission routerPath already exists', 'common'),
('valid.perm.linkPath.NotBlank', 'zh_CN', '权限外链地址不能为空', 'common'),
('valid.perm.linkPath.NotBlank', 'en_US', 'Permission linkPath cannot be blank', 'common'),
('valid.perm.linkPath.patternError', 'zh_CN', '外链地址格式不正确', 'common'),
('valid.perm.linkPath.patternError', 'en_US', 'Permission linkPath is invalid', 'common'),
('valid.perm.permCode.NotBlank', 'zh_CN', '权限编码不能为空', 'common'),
('valid.perm.permCode.NotBlank', 'en_US', 'Permission permCode cannot be blank', 'common'),
('valid.perm.permCode.exist', 'zh_CN', '权限编码已经存在', 'common'),
('valid.perm.permCode.exist', 'en_US', 'Permission permCode exist', 'common'),
('valid.perm.componentName.NotBlank', 'zh_CN', '权限组件名称不能为空', 'common'),
('valid.perm.componentName.NotBlank', 'en_US', 'Permission componentName cannot be blank', 'common'),
('valid.perm.componentPath.NotBlank', 'zh_CN', '权限组件路径不能为空', 'common'),
('valid.perm.componentPath.NotBlank', 'en_US', 'Permission componentPath cannot be blank', 'common'),
('valid.perm.dir.parentError', 'zh_CN', '目录的上级只能是目录', 'common'),
('valid.perm.dir.parentError', 'en_US', 'Parent of a directory must be a directory', 'common'),
('valid.perm.link.parentError', 'zh_CN', '外链的上级只能是目录', 'common'),
('valid.perm.link.parentError', 'en_US', 'Parent of a link must be a directory', 'common'),
('valid.perm.menu.parentError', 'zh_CN', '菜单的上级只能是目录', 'common'),
('valid.perm.menu.parentError', 'en_US', 'Parent of a menu must be a directory', 'common'),
('valid.perm.btn.parentError', 'zh_CN', '按钮的上级只能是目录或菜单', 'common'),
('valid.perm.btn.parentError', 'en_US', 'Parent of a button must be a directory or menu', 'common'),
('valid.perm.parent.notExist', 'zh_CN', '上级权限不存在，请刷新页面后重试', 'common'),
('valid.perm.parent.notExist', 'en_US', 'Parent permission does not exist. Please refresh the page and try again', 'common'),
('valid.perm.permType.notAllowedEdit', 'zh_CN', '权限类型不允许编辑', 'common'),
('valid.perm.permType.notAllowedEdit', 'en_US', 'Permission permType not allowed edit', 'common'),
('valid.perm.permType.invalid', 'zh_CN', '非法的权限类型：{0}', 'common'),
('valid.perm.permType.invalid', 'en_US', 'Invalid permission type: {0}', 'common'),
('valid.perm.delete.hasChild', 'zh_CN', '待删除权限存在子节点，无法被删除，请先删除子节点', 'common'),
('valid.perm.delete.hasChild', 'en_US', 'Cannot delete permission because it has child nodes. Please remove the child nodes first', 'common'),
-- 资源相关
('valid.resource.resourceLevel.configError', 'zh_CN', '路由级别配置错误', 'common'),
('valid.resource.resourceLevel.configError', 'en_US', 'Resource resourceLevel config error', 'common'),
-- 字典相关
('valid.dict.pid.NotNull', 'zh_CN', '字典PID不能为空', 'common'),
('valid.dict.pid.NotNull', 'en_US', 'Dict PID cannot be null', 'common'),
('valid.dict.dictName.NotBlank', 'zh_CN', '字典名称不能为空', 'common'),
('valid.dict.dictName.NotBlank', 'en_US', 'Dict name cannot be blank', 'common'),
('valid.dict.dictType.NotNull', 'zh_CN', '字典类型不能为空', 'common'),
('valid.dict.dictType.NotNull', 'en_US', 'Dict type cannot be null', 'common'),
('valid.dict.dictType.invalid', 'zh_CN', '字典类型不正确，取值范围[1, 2]', 'common'),
('valid.dict.dictType.invalid', 'en_US', 'Invalid dict type. Valid values: [1, 2]', 'common'),
('valid.dict.dictKey.NotBlank', 'zh_CN', '字典KEY不能为空', 'common'),
('valid.dict.dictKey.NotBlank', 'en_US', 'Dict key cannot be blank', 'common'),
('valid.dict.enabled.NotNull', 'zh_CN', '字典状态不能为空', 'common'),
('valid.dict.enabled.NotNull', 'en_US', 'Dict enabled cannot be null', 'common'),
('valid.dict.parent.notExist', 'zh_CN', '上级字典不存在，请刷新页面后重试', 'common'),
('valid.dict.parent.notExist', 'en_US', 'Parent dict does not exist. Please refresh the page and try again', 'common'),
('valid.dict.parentIsNotGroup', 'zh_CN', '上级字典类型不正确', 'common'),
('valid.dict.parentIsNotGroup', 'en_US', 'Parent dict type is invalid', 'common'),
('valid.dict.deleteWithChildren', 'zh_CN', '该字典存在子节点，无法被删除', 'common'),
('valid.dict.deleteWithChildren', 'en_US', 'Cannot delete dict with child nodes', 'common'),
-- 日志相关
('valid.log.logType.NotNull', 'zh_CN', '日志类型不能为空', 'common'),
('valid.log.logType.NotNull', 'en_US', 'Log logType cannot be null', 'common'),
-- 版本相关
('valid.version.versionName.NotBlank', 'zh_CN', '版本名称不能为空', 'common'),
('valid.version.versionName.NotBlank', 'en_US', 'Version ID must not be null', 'common'),
('valid.version.updateContent.NotBlank', 'zh_CN', '修订内容不能为空', 'common'),
('valid.version.updateContent.NotBlank', 'en_US', 'Update content must not be blank', 'common'),
('valid.version.versionName.exist', 'zh_CN', '版本名称已存在', 'common'),
('valid.version.versionName.exist', 'en_US', 'Version name already exists', 'common'),
-- 异常相关 >-->
('error.usercenter.password.decryptExp', 'zh_CN', '参数异常，请刷新页面重试', 'common'),
('error.usercenter.password.decryptExp', 'en_US', 'Log ID cannot be null', 'common');
