USE `zblog`;

DROP TABLE IF EXISTS `i18n_message`;
CREATE TABLE `i18n_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `code` VARCHAR(255) NOT NULL COMMENT '消息代码，建议带前缀标识类别',
  `locale` VARCHAR(20) NOT NULL COMMENT '语言标识，如 zh-CN、en-US',
  `message` VARCHAR(500) NOT NULL COMMENT '国际化文本内容',
  `type` VARCHAR(100) NOT NULL COMMENT '消息类型',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_locale` (`code`, `locale`)
) ENGINE=InnoDB COMMENT='国际化消息表';

INSERT INTO `i18n_message` (`code`, `locale`, `message`, `type`) VALUES
-- 公共错误码 >-->
('ADD_FAILED', 'zh-CN', '新增失败', 'common'),
('ADD_FAILED', 'en-US', 'Failed to add', 'common'),
('EDIT_FAILED', 'zh-CN', '修改失败', 'common'),
('EDIT_FAILED', 'en-US', 'Failed to update', 'common'),
('DELETE_FAILED', 'zh-CN', '删除失败', 'common'),
('DELETE_FAILED', 'en-US', 'Failed to delete', 'common'),
('EMAIL_SEND_ERROR', 'zh-CN', '邮件发送失败', 'common'),
('EMAIL_SEND_ERROR', 'en-US', 'Send email failed', 'common'),
('TECH_PARAM_MISS', 'zh-CN', '技术参数缺失', 'common'),
('TECH_PARAM_MISS', 'en-US', 'Required technical parameter missing', 'common'),
('TECH_PARAM_INVALID1', 'zh-CN', '参数异常[PE001]，请刷新页面后重试', 'common'),
('TECH_PARAM_INVALID1', 'en-US', 'Invalid parameter [PE001]. Please refresh the page and try again', 'common'),
('TECH_PARAM_INVALID2', 'zh-CN', '参数异常[PE002]，请刷新页面后重试', 'common'),
('TECH_PARAM_INVALID2', 'en-US', 'Invalid parameter [PE002]. Please refresh the page and try again', 'common'),
('TECH_PARAM_INVALID3', 'zh-CN', '参数异常[PE003]，请重新登录后再试', 'common'),
('TECH_PARAM_INVALID3', 'en-US', 'Invalid parameter [PE003]. Please log in again and try', 'common'),
('DATA_ENCRYPT_FAILED', 'zh-CN', '数据加密失败', 'common'),
('DATA_ENCRYPT_FAILED', 'en-US', 'Data encryption failed', 'common'),
('DATA_DECRYPT_FAILED', 'zh-CN', '数据解密失败', 'common'),
('DATA_DECRYPT_FAILED', 'en-US', 'Data decryption failed', 'common'),
('DATA_NOT_FOUND', 'zh-CN', '数据不存在，请刷新页面后重试', 'common'),
('DATA_NOT_FOUND', 'en-US', 'Data not found. Please refresh the page and try again', 'common'),
('PARAM_SORT_REQUIRED', 'zh-CN', '请输入排序值', 'common'),
('PARAM_SORT_REQUIRED', 'en-US', 'Please enter a sort value', 'common'),
('PARAM_SORT_MAX99999', 'zh-CN', '排序值不能超过 99999，请重新输入', 'common'),
('PARAM_SORT_MAX99999', 'en-US', 'Sort value cannot exceed 99999. please enter again', 'common'),
('PARAM_SORT_MIN1', 'zh-CN', '排序值不能小于 1，请重新输入', 'common'),
('PARAM_SORT_MIN1', 'en-US', 'Sort value cannot be less than 1. please enter again', 'common'),
-- 校验相关 >-->
-- 公共校验
('valid.comm.param.NotNull', 'zh-CN', '必要参数未提供，请检查输入', 'common'),
('valid.comm.param.NotNull', 'en-US', 'Required parameter missing, please check your input', 'common'),
('valid.comm.param.NotBlank', 'zh-CN', '必要参数未提供或为空，请检查输入', 'common'),
('valid.comm.param.NotBlank', 'en-US', 'Required parameter missing or blank, please check your input', 'common'),
-- 用户相关
('USER_NOT_EXISTS', 'zh-CN', '用户不存在', 'common'),
('USER_NOT_EXISTS', 'en-US', 'User does not exist', 'common'),
('USER_USERNAME_REQUIRED', 'zh-CN', '用户名不能为空', 'common'),
('USER_USERNAME_REQUIRED', 'en-US', 'Username cannot be blank', 'common'),
('USER_USERNAME_EXISTS', 'zh-CN', '用户名已存在', 'common'),
('USER_USERNAME_EXISTS', 'en-US', 'Username already exists', 'common'),
('USER_USERNAME_PATTERN_INVALID', 'zh-CN', '用户名格式错误', 'common'),
('USER_USERNAME_PATTERN_INVALID', 'en-US', 'Username pattern is invalid', 'common'),
('USER_USERNAME_IMMUTABLE', 'zh-CN', '用户名禁止修改', 'common'),
('USER_USERNAME_IMMUTABLE', 'en-US', 'Username cannot be modified', 'common'),
('USER_EMAIL_REQUIRED', 'zh-CN', '邮箱不能为空', 'common'),
('USER_EMAIL_REQUIRED', 'en-US', 'Email cannot be blank', 'common'),
('USER_EMAIL_ALREADY_EXISTS', 'zh-CN', '邮箱已注册', 'common'),
('USER_EMAIL_ALREADY_EXISTS', 'en-US', 'Email already registered', 'common'),
('USER_EMAIL_PATTERN_INVALID', 'zh-CN', '邮箱格式错误', 'common'),
('USER_EMAIL_PATTERN_INVALID', 'en-US', 'Email pattern is invalid', 'common'),
('USER_USERTYPE_REQUIRED', 'zh-CN', '用户类型不能为空', 'common'),
('USER_USERTYPE_REQUIRED', 'en-US', 'UserType cannot be blank', 'common'),
('USER_USERSTATUS_REQUIRED', 'zh-CN', '用户状态不能为空', 'common'),
('USER_USERSTATUS_REQUIRED', 'en-US', 'UserStatus cannot be blank', 'common'),
('USER_NICKNAME_ALREADY_EXISTS', 'zh-CN', '用户昵称已存在', 'common'),
('USER_NICKNAME_ALREADY_EXISTS', 'en-US', 'Nickname already exists', 'common'),
('USER_EXPIRETIME_REQUIRED_WITH_TEMP', 'zh-CN', '临时用户账号有效期不能为空', 'common'),
('USER_EXPIRETIME_REQUIRED_WITH_TEMP', 'en-US', 'Temp user expireTime cannot be blank', 'common'),
('USER_NO_DATA_OPE_PERMISSION', 'zh-CN', '没有数据操作权限', 'common'),
('USER_NO_DATA_OPE_PERMISSION', 'en-US', 'You do not have permission to operate this user', 'common'),
('USER_NO_PERMISSION_TO_DELETE_SELF', 'zh-CN', '无法删除自己', 'common'),
('USER_NO_PERMISSION_TO_DELETE_SELF', 'en-US', 'Deleting your own account is not allowed', 'common'),
-- 用户中心相关
('USERCENTER_OLD_PASSWORD_REQUIRED', 'zh-CN', '原密码不能为空', 'common'),
('USERCENTER_OLD_PASSWORD_REQUIRED', 'en-US', 'Current password is required', 'common'),
('USERCENTER_NEW_PASSWORD_REQUIRED', 'zh-CN', '新密码不能为空', 'common'),
('USERCENTER_NEW_PASSWORD_REQUIRED', 'en-US', 'New password is required', 'common'),
('USERCENTER_CONFIRM_PASSWORD_REQUIRED', 'zh-CN', '确认密码不能为空', 'common'),
('USERCENTER_CONFIRM_PASSWORD_REQUIRED', 'en-US', 'Confirm password is required', 'common'),
('USERCENTER_NEW_PASSWORD_MISMATCH', 'zh-CN', '两次输入的新密码不一致', 'common'),
('USERCENTER_NEW_PASSWORD_MISMATCH', 'en-US', 'The new passwords do not match', 'common'),
('USERCENTER_PASSWORD_WITH_USER_MISS', 'zh-CN', '用户信息异常，请刷新页面后重试', 'common'),
('USERCENTER_PASSWORD_WITH_USER_MISS', 'en-US', 'User information is invalid. Please log in again and try', 'common'),
('USERCENTER_OLD_PASSWORD_MISMATCH', 'zh-CN', '原密码错误', 'common'),
('USERCENTER_OLD_PASSWORD_MISMATCH', 'en-US', 'Current password is incorrect', 'common'),
('USERCENTER_NEW_PASSWORD_SAMEWITHOLD', 'zh-CN', '新密码与原密码不能相同', 'common'),
('USERCENTER_NEW_PASSWORD_SAMEWITHOLD', 'en-US', 'New password cannot be the same as the current password', 'common'),
('USERCENTER_NEW_PASSWORD_CONTAIN_USER', 'zh-CN', '密码不能包含用户名', 'common'),
('USERCENTER_NEW_PASSWORD_CONTAIN_USER', 'en-US', 'Password cannot contain the username', 'common'),
('USERCENTER_NEW_PASSWORD_LOW_COMPLEXITY', 'zh-CN', '密码长度必须大于等于6位且小于等于20位，需要包含大写字母，小写字母，数字，特殊字符中的至少两种', 'common'),
('USERCENTER_NEW_PASSWORD_LOW_COMPLEXITY', 'en-US', 'Password must be 6-20 characters long and include at least two of the following: uppercase letters, lowercase letters, numbers, special characters', 'common'),
('USERCENTER_NEW_PASSWORD_SAMEWITHHIS', 'zh-CN', '新密码不能与最近{0}次密码重复', 'common'),
('USERCENTER_NEW_PASSWORD_SAMEWITHHIS', 'en-US', 'New password cannot be the same as the last {0} passwords', 'common'),
('USERCENTER_IMAGE_REQUIRED', 'zh-CN', '头像上传失败，请稍后再试', 'common'),
('USERCENTER_IMAGE_REQUIRED', 'en-US', 'Avatar upload failed, please refresh the page and try again', 'common'),
('USERCENTER_IMAGE_FILE_MISS', 'zh-CN', '头像上传失败，请稍后再试', 'common'),
('USERCENTER_IMAGE_FILE_MISS', 'en-US', 'Avatar upload failed, please refresh the page and try again', 'common'),
('USERCENTER_EMAIL_REQUIRED', 'zh-CN', '邮箱不能为空', 'common'),
('USERCENTER_EMAIL_REQUIRED', 'en-US', 'Email cannot be blank', 'common'),
('USERCENTER_EMAIL_CODE_REQUIRED', 'zh-CN', '邮箱验证码不能为空', 'common'),
('USERCENTER_EMAIL_CODE_REQUIRED', 'en-US', 'Email code cannot be blank', 'common'),
('USERCENTER_EMAIL_UUID_REQUIRED', 'zh-CN', '验证码获取失败，请稍后再试', 'common'),
('USERCENTER_EMAIL_UUID_REQUIRED', 'en-US', 'Failed to get email code. Please try again later', 'common'),
('USERCENTER_EMAIL_CODE_EXPIRED', 'zh-CN', '邮箱验证码已过期', 'common'),
('USERCENTER_EMAIL_CODE_EXPIRED', 'en-US', 'Email code has expired', 'common'),
('USERCENTER_EMAIL_CODE_INVALID', 'zh-CN', '邮箱验证码不正确', 'common'),
('USERCENTER_EMAIL_CODE_INVALID', 'en-US', 'Email code is incorrect', 'common'),
('USERCENTER_EMAIL_SAMEWITHOLD', 'zh-CN', '新邮箱不能与旧邮箱相同', 'common'),
('USERCENTER_EMAIL_SAMEWITHOLD', 'en-US', 'New email cannot be the same as the old email', 'common'),
('USERCENTER_EMAIL_PATTERN_INVALID', 'zh-CN', '邮箱格式不正确', 'common'),
('USERCENTER_EMAIL_PATTERN_INVALID', 'en-US', 'Email pattern is invalid', 'common'),
('USERCENTER_EMAIL_EXISTS', 'zh-CN', '邮箱已被其他账号绑定', 'common'),
('USERCENTER_EMAIL_EXISTS', 'en-US', 'This email is already linked to another account', 'common'),
('USERCENTER_PROFILE_NICKNAME_REQUIRED', 'zh-CN', '用户昵称不能为空', 'common'),
('USERCENTER_PROFILE_NICKNAME_REQUIRED', 'en-US', 'Nickname cannot be blank', 'common'),
('USERCENTER_PROFILE_NICKNAME_EXISTS', 'zh-CN', '昵称已存在，请换一个', 'common'),
('USERCENTER_PROFILE_NICKNAME_EXISTS', 'en-US', 'Nickname already exists, please choose another', 'common'),
('USERCENTER_PROFILE_GENDER_REQUIRED', 'zh-CN', '用户性别不能为空', 'common'),
('USERCENTER_PROFILE_GENDER_REQUIRED', 'en-US', 'Gender cannot be empty', 'common'),
('USERCENTER_PROFILE_GENDER_INVALID', 'zh-CN', '用户性别不合法', 'common'),
('USERCENTER_PROFILE_GENDER_INVALID', 'en-US', 'Invalid gender value', 'common'),
('USERCENTER_PASSWORD_FAILED', 'zh-CN', '密码修改失败', 'common'),
('USERCENTER_PASSWORD_FAILED', 'en-US', 'Failed to update password', 'common'),
('USERCENTER_IMAGE_FAILED', 'zh-CN', '头像修改失败', 'common'),
('USERCENTER_IMAGE_FAILED', 'en-US', 'Failed to update image', 'common'),
('USERCENTER_EMAIL_FAILED', 'zh-CN', '邮箱修改失败', 'common'),
('USERCENTER_EMAIL_FAILED', 'en-US', 'Failed to update email', 'common'),
('USERCENTER_PROFILE_FAILED', 'zh-CN', '信息修改失败', 'common'),
('USERCENTER_PROFILE_FAILED', 'en-US', 'Failed to update profile information', 'common'),
-- 角色相关
('ROLE_ROLENAME_REQUIRED', 'zh-CN', '角色名称不能为空', 'common'),
('ROLE_ROLENAME_REQUIRED', 'en-US', 'RoleName cannot be blank', 'common'),
('ROLE_ROLENAME_EXISTS', 'zh-CN', '角色名称已存在', 'common'),
('ROLE_ROLENAME_EXISTS', 'en-US', 'RoleName already exists', 'common'),
('ROLE_ROLECODE_REQUIRED', 'zh-CN', '角色编码不能为空', 'common'),
('ROLE_ROLECODE_REQUIRED', 'en-US', 'RoleCode cannot be blank', 'common'),
('ROLE_ROLECODE_EXISTS', 'zh-CN', '角色编码已存在', 'common'),
('ROLE_ROLECODE_EXISTS', 'en-US', 'RoleCode already exists', 'common'),
('ROLE_ROLECODE_PATTERN_INVALID', 'zh-CN', '角色编码格式不正确', 'common'),
('ROLE_ROLECODE_PATTERN_INVALID', 'en-US', 'RoleCode pattern is invalid', 'common'),
('ROLE_ROLECODE_DISABLED', 'zh-CN', '角色编码不可用', 'common'),
('ROLE_ROLECODE_DISABLED', 'en-US', 'RoleCode is disabled', 'common'),
('ROLE_ENABLED_REQUIRED', 'zh-CN', '角色状态不能为空', 'common'),
('ROLE_ENABLED_REQUIRED', 'en-US', 'Role status cannot be blank', 'common'),
('ROLE_DELETE_WITH_USER', 'zh-CN', '角色已与用户关联，请解除关联后再试', 'common'),
('ROLE_DELETE_WITH_USER', 'en-US', 'Role is associated with users. please unbind before deletion', 'common'),
-- 权限相关
('PERM_NAME_REQUIRED', 'zh-CN', '权限名称不能为空', 'common'),
('PERM_NAME_REQUIRED', 'en-US', 'Permission name cannot be blank', 'common'),
('PERM_TYPE_REQUIRED', 'zh-CN', '权限类型不能为空', 'common'),
('PERM_TYPE_REQUIRED', 'en-US', 'Permission type cannot be blank', 'common'),
('PERM_LEVEL_REQUIRED', 'zh-CN', '权限等级不能为空', 'common'),
('PERM_LEVEL_REQUIRED', 'en-US', 'Permission level cannot be blank', 'common'),
('PERM_ENABLED_REQUIRED', 'zh-CN', '权限状态不能为空', 'common'),
('PERM_ENABLED_REQUIRED', 'en-US', 'Permission status cannot be blank', 'common'),
('PERM_HIDDEN_REQUIRED', 'zh-CN', '菜单可见不能为空', 'common'),
('PERM_HIDDEN_REQUIRED', 'en-US', 'Permission hidden cannot be blank', 'common'),
('PERM_CACHEABLE_REQUIRED', 'zh-CN', '菜单缓存不能为空', 'common'),
('PERM_CACHEABLE_REQUIRED', 'en-US', 'Permission cacheable cannot be blank', 'common'),
('PERM_ROUTERPATH_REQUIRED', 'zh-CN', '路由地址不能为空', 'common'),
('PERM_ROUTERPATH_REQUIRED', 'en-US', 'Permission routerPath cannot be blank', 'common'),
('PERM_ROUTERPATH_PATTERN_INVALID', 'zh-CN', '路由地址格式不正确', 'common'),
('PERM_ROUTERPATH_PATTERN_INVALID', 'en-US', 'Permission routerPath is invalid', 'common'),
('PERM_ROUTERPATH_EXISTS', 'zh-CN', '路由地址已存在', 'common'),
('PERM_ROUTERPATH_EXISTS', 'en-US', 'Permission routerPath already exists', 'common'),
('PERM_LINKPATH_REQUIRED', 'zh-CN', '权限外链地址不能为空', 'common'),
('PERM_LINKPATH_REQUIRED', 'en-US', 'Permission linkPath cannot be blank', 'common'),
('PERM_LINKPATH_PATTERN_INVALID', 'zh-CN', '外链地址格式不正确', 'common'),
('PERM_LINKPATH_PATTERN_INVALID', 'en-US', 'Permission linkPath is invalid', 'common'),
('PERM_PERMCODE_REQUIRED', 'zh-CN', '权限编码不能为空', 'common'),
('PERM_PERMCODE_REQUIRED', 'en-US', 'Permission permCode cannot be blank', 'common'),
('PERM_PERMCODE_EXISTS', 'zh-CN', '权限编码已存在', 'common'),
('PERM_PERMCODE_EXISTS', 'en-US', 'Permission permCode exist', 'common'),
('PERM_COMPONENTNAME_REQUIRED', 'zh-CN', '权限组件名称不能为空', 'common'),
('PERM_COMPONENTNAME_REQUIRED', 'en-US', 'Permission componentName cannot be blank', 'common'),
('PERM_COMPONENTPATH_REQUIRED', 'zh-CN', '权限组件路径不能为空', 'common'),
('PERM_COMPONENTPATH_REQUIRED', 'en-US', 'Permission componentPath cannot be blank', 'common'),
('PERM_DIR_PARENT', 'zh-CN', '目录的上级只能是目录', 'common'),
('PERM_DIR_PARENT', 'en-US', 'Parent of a directory must be a directory', 'common'),
('PERM_LINK_PARENT', 'zh-CN', '外链的上级只能是目录', 'common'),
('PERM_LINK_PARENT', 'en-US', 'Parent of a link must be a directory', 'common'),
('PERM_MENU_PARENT', 'zh-CN', '菜单的上级只能是目录', 'common'),
('PERM_MENU_PARENT', 'en-US', 'Parent of a menu must be a directory', 'common'),
('PERM_BTN_PARENT', 'zh-CN', '按钮的上级只能是目录或菜单', 'common'),
('PERM_BTN_PARENT', 'en-US', 'Parent of a button must be a directory or menu', 'common'),
('PERM_PARENT_NOT_EXISTS', 'zh-CN', '上级权限不存在，请刷新页面后重试', 'common'),
('PERM_PARENT_NOT_EXISTS', 'en-US', 'Parent permission does not exist. Please refresh the page and try again', 'common'),
('PERM_PERMTYPE_EDIT_DISABLED', 'zh-CN', '权限类型不允许编辑', 'common'),
('PERM_PERMTYPE_EDIT_DISABLED', 'en-US', 'Permission permType not allowed edit', 'common'),
('PERM_DELETE_WITH_CHILDREN', 'zh-CN', '该权限存在子节点，无法被删除，请先删除子节点', 'common'),
('PERM_DELETE_WITH_CHILDREN', 'en-US', 'Cannot delete permission because it has child nodes. Please remove the child nodes first', 'common'),
-- 字典相关
('DICT_DICTNAME_REQUIRED', 'zh-CN', '字典名称不能为空', 'common'),
('DICT_DICTNAME_REQUIRED', 'en-US', 'Dict name cannot be blank', 'common'),
('DICT_DICTKEY_REQUIRED', 'zh-CN', '字典KEY不能为空', 'common'),
('DICT_DICTKEY_REQUIRED', 'en-US', 'Dict key cannot be blank', 'common'),
('DICT_ENABLED_REQUIRED', 'zh-CN', '字典状态不能为空', 'common'),
('DICT_ENABLED_REQUIRED', 'en-US', 'Dict status cannot be blank', 'common'),
('DICT_PARENT_NOT_EXISTS', 'zh-CN', '上级字典不存在，请刷新页面后重试', 'common'),
('DICT_PARENT_NOT_EXISTS', 'en-US', 'Parent dict does not exist. Please refresh the page and try again', 'common'),
('DICT_PARENT_TYPE_INVALID', 'zh-CN', '上级字典类型不正确，请刷新页面后重试', 'common'),
('DICT_PARENT_TYPE_INVALID', 'en-US', 'Parent dict type is invalid. Please refresh the page and try again', 'common'),
('DICT_DELETE_WITH_CHILDREN', 'zh-CN', '该字典存在子节点，无法被删除', 'common'),
('DICT_DELETE_WITH_CHILDREN', 'en-US', 'Cannot delete dict with child nodes', 'common'),
-- 版本相关
('VERSION_VERSIONNAME_REQUIRED', 'zh-CN', '版本名称不能为空', 'common'),
('VERSION_VERSIONNAME_REQUIRED', 'en-US', 'Version name cannot be blank', 'common'),
('VERSION_UPDATECONTENT_REQUIRED', 'zh-CN', '修订内容不能为空', 'common'),
('VERSION_UPDATECONTENT_REQUIRED', 'en-US', 'Update content cannot be blank', 'common'),
('VERSION_VERSIONNAME_EXISTS', 'zh-CN', '版本已存在', 'common'),
('VERSION_VERSIONNAME_EXISTS', 'en-US', 'Version already exists', 'common'),
-- 存储相关
('valid.file.common.fileNotExist', 'zh-CN', '文件不存在或已被删除', 'common'),
('valid.file.common.fileNotExist', 'en-US', 'The file does not exist or has already been deleted', 'common'),
('valid.file.upload.chooseNoneFile', 'zh-CN', '上传失败，待上传文件列表为空', 'common'),
('valid.file.upload.chooseNoneFile', 'en-US', 'Upload failed: no files selected for upload', 'common'),
('valid.file.upload.switchOff', 'zh-CN', '上传失败，文件上传未启用', 'common'),
('valid.file.upload.switchOff', 'en-US', 'Upload failed: file upload is disabled', 'common'),
('valid.file.upload.notSupport', 'zh-CN', '上传失败，不支持的文件类型 {0}', 'common'),
('valid.file.upload.notSupport', 'en-US', 'Upload failed: unsupported file type {0}', 'common'),
('valid.file.upload.notWhiteList', 'zh-CN', '上传失败，不支持的文件类型 [{0}]', 'common'),
('valid.file.upload.notWhiteList', 'en-US', 'Upload failed: file type not in whitelist [{0}]', 'common'),
('valid.file.upload.imageInvalid', 'zh-CN', '上传失败，图片内容校验失败', 'common'),
('valid.file.upload.imageInvalid', 'en-US', 'Upload failed: image content validation failed', 'common'),
('valid.file.upload.imageRadioMax', 'zh-CN', '上传失败，图片分辨率过大', 'common'),
('valid.file.upload.imageRadioMax', 'en-US', 'Upload failed: image resolution is too large', 'common'),
('valid.file.upload.sizeOverMax', 'zh-CN', '上传失败，文件大小不能超过 {0} kb', 'common'),
('valid.file.upload.sizeOverMax', 'en-US', 'Upload failed: file size must not exceed {0} KB', 'common'),
('valid.file.upload.insertDbFailed', 'zh-CN', '上传失败，数据库异常，请稍后再试', 'common'),
('valid.file.upload.insertDbFailed', 'en-US', 'Upload failed due to a database error. Please try again later', 'common'),
('valid.file.delete.hasBusiness', 'zh-CN', '文件已关联业务数据，无法删除', 'common'),
('valid.file.delete.hasBusiness', 'en-US', 'The file is associated with business data and cannot be deleted', 'common'),
('valid.file.delete.logicFailed', 'zh-CN', '删除文件记录失败，请稍后再试', 'common'),
('valid.file.delete.logicFailed', 'en-US', 'Failed to delete file record. Please try again later', 'common'),
('valid.file.delete.hasReference', 'zh-CN', '文件仍被其他业务引用，无法删除', 'common'),
('valid.file.delete.hasReference', 'en-US', 'The file is still referenced by other records and cannot be deleted', 'common'),
('valid.file.delete.storageFailed', 'zh-CN', '删除物理文件记录失败，请稍后再试', 'common'),
('valid.file.delete.storageFailed', 'en-US', 'Failed to delete physical file record. Please try again later', 'common');
