/*Table structure for table `page` */
DROP TABLE IF EXISTS `page`;
CREATE TABLE `page` (
  `ID` BIGINT UNSIGNED NOT NULL COMMENT '页面编号',
  `PAGE_NAME` VARCHAR(50) NOT NULL COMMENT '页面名称',
  `PAGE_LABEL` VARCHAR(50) NOT NULL COMMENT '页面标识',
  `DISPLAY_MODE` VARCHAR(50) NOT NULL COMMENT '页面展示模式',
  `PAGE_SORT` INT NOT NULL DEFAULT 99999 COMMENT '页面排序',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC COMMENT='页面表';

CREATE UNIQUE INDEX uk_page_label ON page(`PAGE_LABEL`);

/*Data for the table `page` */
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550262842852638720, '首页', 'home', 'FULL', 1, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550263063359782912, '分类', 'category', 'BANNER', 2, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550263198819024896, '标签', 'tag', 'BANNER', 3, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550263325503782912, '专栏', 'column', 'BANNER', 4, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550302122887086080, '文章', 'article', 'BANNER', 5, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550302704641245184, '文章列表', 'articles', 'BANNER', 6, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550303326471979008, '归档', 'archive', 'BANNER', 7, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550312241301553152, '相册', 'album', 'BANNER', 8, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550312375179542528, '说说', 'talk', 'BANNER', 9, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550320281232867328, '友链', 'link', 'BANNER', 10, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3550320794401767424, '弹幕', 'message', 'FULL', 11, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3560832866961063936, '个人中心', 'user', 'BANNER', 12, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3562305820047704064, '404', '404', 'BANNER', 13, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3562312827270070272, '文章不存在', 'article404', 'BANNER', 14, 1, '2021-06-10 00:02:58', NULL, NULL);
INSERT INTO page (ID, PAGE_NAME, PAGE_LABEL, DISPLAY_MODE, PAGE_SORT, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME) VALUES (3570495375699615744, '统计', 'statistics', 'BANNER', 16, 1, '2021-06-10 00:02:58', NULL, NULL);

/*Table structure for table `theme` */
DROP TABLE IF EXISTS `theme`;
CREATE TABLE `theme` (
  `ID` BIGINT UNSIGNED NOT NULL COMMENT '主题编号',
  `THEME_NAME` VARCHAR(100) NOT NULL COMMENT '主题名称',
  `THEME_TYPE` VARCHAR(50) NOT NULL COMMENT '主题类型：PC，MOBILE',
  `OWNER_TYPE` VARCHAR(50) NOT NULL COMMENT '主题归属：SYSTEM-系统主题，USER-用户主题',
  `OWNER_ID` BIGINT DEFAULT NULL COMMENT '所属用户',
  `IS_DEFAULT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统默认主题',
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否当前激活主题',
  `PREVIEW_COVER` VARCHAR(500) DEFAULT NULL COMMENT '主题预览图',
  `DESCRIPTION` VARCHAR(200) DEFAULT NULL COMMENT '主题描述',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC COMMENT='主题表';

CREATE INDEX idx_theme_owner ON theme(`OWNER_TYPE`, `OWNER_ID`);
CREATE INDEX idx_theme_default ON theme(`THEME_TYPE`, `IS_DEFAULT`);
CREATE UNIQUE INDEX uk_theme_name_owner ON theme(`OWNER_ID`, `THEME_TYPE`, `THEME_NAME`);

/*Table structure for table `theme_page` */
DROP TABLE IF EXISTS `theme_page`;
CREATE TABLE `theme_page` (
  `ID` BIGINT UNSIGNED NOT NULL COMMENT '主题页面编号',
  `THEME_ID` BIGINT NOT NULL COMMENT '主题编号',
  `PAGE_ID` BIGINT NOT NULL COMMENT '页面编号',
  `PAGE_COVER` VARCHAR(500) NOT NULL COMMENT '页面预览图',
  `VERSION` INT(11) NOT NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATE_USER` BIGINT NOT NULL COMMENT '创建用户',
  `CREATE_TIME` VARCHAR(20) NOT NULL COMMENT '创建时间',
  `UPDATE_USER` BIGINT DEFAULT NULL COMMENT '更新用户',
  `UPDATE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC COMMENT='主题页面配置表';

CREATE INDEX idx_theme_page ON theme_page(`THEME_ID`, `PAGE_ID`);
